USE ROLE ACCOUNTADMIN;
ALTER SNOWFLAKE INTELLIGENCE IF EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
  DROP AGENT SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.CFO_ASSISTANT;

USE ROLE SYSADMIN;

DROP STREAMLIT IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.IOT_LIFECYCLE_DASHBOARD;
DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.CFO_ASSISTANT;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_IOT_FINANCIAL;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.REFRESH_FLEET_STATUS;
DROP STREAM IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.GPS_TELEMETRY_STREAM;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_REVENUE_BY_CUSTOMER;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_FINANCIAL_SUMMARY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_ROUTE_EFFICIENCY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_GARMENT_LOSS_RATE;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_GARMENT_LIFECYCLE;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_FLEET_STATUS;
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE CASCADE;
DROP WAREHOUSE IF EXISTS SFE_IOT_LIFECYCLE_WH;

SELECT 'Teardown complete!' AS status;
