USE ROLE ACCOUNTADMIN;
ALTER SNOWFLAKE INTELLIGENCE IF EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
  DROP AGENT SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.CFO_ASSISTANT;

DROP EXTERNAL ACCESS INTEGRATION IF EXISTS OSM_TILES_ACCESS;

USE ROLE SYSADMIN;

DROP SERVICE IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.FLEET_DASHBOARD_SERVICE;
DROP COMPUTE POOL IF EXISTS IOT_FLEET_POOL;
DROP IMAGE REPOSITORY IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.IOT_IMAGE_REPO;
DROP NETWORK RULE IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.OSM_TILES_RULE;
DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.CFO_ASSISTANT;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_IOT_FINANCIAL;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.REFRESH_FLEET_STATUS;
DROP STREAM IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.GPS_TELEMETRY_STREAM;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_REVENUE_BY_CUSTOMER;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_FINANCIAL_SUMMARY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_ROUTE_EFFICIENCY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_GARMENT_LOSS_RATE;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_GARMENT_LIFECYCLE;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.V_FLEET_STATUS;
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE CASCADE;
DROP WAREHOUSE IF EXISTS SFE_IOT_LIFECYCLE_WH;

SELECT 'Teardown complete!' AS status;
