USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_REST_API_COST;

CREATE OR REPLACE STREAMLIT CORTEX_REST_API_COST_APP
  FROM '@SNOWFLAKE_EXAMPLE.GIT_REPOS.SFE_DEMOS_REPO/branches/main/tool-cortex-rest-api-cost/streamlit/cortex_rest_api_cost/'
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = SFE_CORTEX_REST_API_COST_WH
  COMMENT = 'TOOL: Cortex REST API Cost Dashboard (Expires: 2026-04-22)'
  TITLE = 'Cortex API Cost';

ALTER STREAMLIT CORTEX_REST_API_COST_APP ADD LIVE VERSION FROM LAST;

GRANT USAGE ON STREAMLIT CORTEX_REST_API_COST_APP TO ROLE PUBLIC;
