USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_REST_API_COST;

CREATE OR REPLACE NOTEBOOK CORTEX_REST_API_COST_NOTEBOOK
  FROM '@SNOWFLAKE_EXAMPLE.GIT_REPOS.SFE_DEMOS_REPO/branches/main/tool-cortex-rest-api-cost/notebook/'
  MAIN_FILE = 'cortex_rest_api_cost.ipynb'
  QUERY_WAREHOUSE = SFE_CORTEX_REST_API_COST_WH
  COMMENT = 'TOOL: Cortex REST API Cost query walkthrough (Expires: 2026-04-22)';

ALTER NOTEBOOK CORTEX_REST_API_COST_NOTEBOOK ADD LIVE VERSION FROM LAST;
