/******************************************************************************
 * DR Cost Agent - DB_METADATA_V2
 * Hybrid-table-aware database sizing for replication cost estimation.
 * Hybrid tables are SKIPPED during replication refresh (BCR-1560-1582);
 * REPLICABLE_SIZE_TB excludes them for accurate projections.
 ******************************************************************************/

USE SCHEMA SNOWFLAKE_EXAMPLE.DR_COST_AGENT;

CREATE OR REPLACE VIEW DB_METADATA_V2
    COMMENT = 'TOOL: Database sizes with hybrid table exclusion for replication sizing (Expires: 2026-05-01)'
AS
WITH ALL_DBS AS (
    SELECT DATABASE_NAME
    FROM INFORMATION_SCHEMA.DATABASES
    WHERE DATABASE_NAME NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'UTIL_DB')
),
DB_STORAGE AS (
    SELECT
        TABLE_CATALOG AS DATABASE_NAME,
        SUM(ACTIVE_BYTES) AS TOTAL_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE TABLE_CATALOG NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'UTIL_DB')
      AND DELETED IS NULL
    GROUP BY TABLE_CATALOG
),
HYBRID_STORAGE AS (
    SELECT
        TABLE_CATALOG AS DATABASE_NAME,
        COUNT(*) AS HYBRID_TABLE_COUNT,
        COALESCE(SUM(BYTES), 0) AS HYBRID_TABLE_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.HYBRID_TABLES
    WHERE DELETED IS NULL
    GROUP BY TABLE_CATALOG
)
SELECT
    d.DATABASE_NAME,
    COALESCE((s.TOTAL_BYTES / POWER(1024, 4)), 0)::NUMBER(18,6) AS TOTAL_SIZE_TB,
    COALESCE((h.HYBRID_TABLE_BYTES / POWER(1024, 4)), 0)::NUMBER(18,6) AS HYBRID_EXCLUDED_TB,
    (COALESCE((s.TOTAL_BYTES / POWER(1024, 4)), 0)
     - COALESCE((h.HYBRID_TABLE_BYTES / POWER(1024, 4)), 0))::NUMBER(18,6) AS REPLICABLE_SIZE_TB,
    COALESCE(h.HYBRID_TABLE_COUNT, 0) AS HYBRID_TABLE_COUNT,
    CASE WHEN COALESCE(h.HYBRID_TABLE_COUNT, 0) > 0 THEN TRUE ELSE FALSE END AS HAS_HYBRID_TABLES,
    CURRENT_TIMESTAMP() AS QUERIED_AT,
    DATEDIFF('hour',
        (SELECT MAX(LAST_ALTERED) FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
         WHERE DELETED IS NULL),
        CURRENT_TIMESTAMP()
    ) AS DATA_STALENESS_HOURS
FROM ALL_DBS d
LEFT JOIN DB_STORAGE s ON d.DATABASE_NAME = s.DATABASE_NAME
LEFT JOIN HYBRID_STORAGE h ON d.DATABASE_NAME = h.DATABASE_NAME;
