/*=============================================================================
  98_validation/02_first_batch_pending_tests.sql
  Snowflake Streams CDC Workshop - First Batch Before-Consumption Proof
  Pair-programmed by SE Community + Cortex Code | Expires: 2026-10-08
=============================================================================*/

USE ROLE SYSADMIN;
USE WAREHOUSE SFE_STREAMS_CDC_WH;
USE SCHEMA SNOWFLAKE_EXAMPLE.STREAMS_CDC_WORKSHOP;

WITH COUNTS AS (
  SELECT
    COUNT(*) AS CDC_ROWS,
    COUNT_IF(METADATA$ACTION = 'INSERT' AND NOT METADATA$ISUPDATE) AS INSERT_ROWS,
    COUNT_IF(METADATA$ACTION = 'INSERT' AND METADATA$ISUPDATE) AS UPDATE_AFTER_ROWS,
    COUNT_IF(METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE) AS UPDATE_BEFORE_ROWS,
    COUNT_IF(METADATA$ACTION = 'DELETE' AND NOT METADATA$ISUPDATE) AS DELETE_ROWS
  FROM RAW_ORDERS_STREAM
)
SELECT
  IFF(CDC_ROWS = 4, 'PASS', 'FAIL') AS FOUR_CDC_ROWS,
  IFF(INSERT_ROWS = 1, 'PASS', 'FAIL') AS ONE_INSERT,
  IFF(UPDATE_AFTER_ROWS = 1 AND UPDATE_BEFORE_ROWS = 1, 'PASS', 'FAIL') AS ONE_UPDATE_PAIR,
  IFF(DELETE_ROWS = 1, 'PASS', 'FAIL') AS ONE_DELETE
FROM COUNTS;
