/*
  guide-openflow-shopify-multistore — 06_analytics_layer.sql
  Pair-programmed by SE Community + Cortex Code
  Expires: 2026-12-03

  PURPOSE
    Turn N per-store schemas into one queryable model:
      SHOPIFY_ANALYTICS.ORDERS_ALL            (UNION ALL of every store's ORDERS)
      SHOPIFY_ANALYTICS.ORDER_LINE_ITEMS_ALL
      SHOPIFY_ANALYTICS.ORDER_FULFILLMENTS_ALL
      SHOPIFY_ANALYTICS.DAILY_SHOP_ACTIVITY   (one row per store per day)
      SHOPIFY_ANALYTICS.STORE_FRESHNESS       (ops view: hours since last update)

    The UNION ALL Dynamic Tables are GENERATED by REBUILD_ANALYTICS_DTS() from
    STORE_REGISTRY. Re-run it every time a store is added or deactivated.

  COLUMN CONTRACT
    Columns referenced here are the promoted columns defined in
    config/shopify_object_override.json plus the connector's own columns:
      ID, SHOP_URL (merge key), __PARENT_ID (child tables),
      __SNOWFLAKE_IS_DELETED, __SNOWFLAKE_DELETED_AT.
    The raw JSON payload column name is NOT documented. After the first store
    loads, run  DESCRIBE TABLE SHOPIFY_RAW.<STORE>.ORDERS  and, if any column
    below is missing, adjust the override or this file before rebuilding.

  RUN AS      OPENFLOW_ADMIN
  RUNTIME     < 1 minute to create; first DT refresh depends on data volume
  SOURCE      https://docs.snowflake.com/en/user-guide/dynamic-tables/overview
*/

USE ROLE OPENFLOW_ADMIN;

CREATE DATABASE IF NOT EXISTS SHOPIFY_ANALYTICS
  COMMENT = 'Cross-store Shopify analytics layer (Dynamic Tables)';

CREATE SCHEMA IF NOT EXISTS SHOPIFY_ANALYTICS.CORE
  COMMENT = 'Consolidated orders, line items, fulfillments, daily activity';

-- Dedicated warehouse for DT refreshes so ingestion cost stays separable
CREATE WAREHOUSE IF NOT EXISTS SHOPIFY_ANALYTICS_WH
  WAREHOUSE_SIZE               = 'XSMALL'
  AUTO_SUSPEND                 = 60
  AUTO_RESUME                  = TRUE
  INITIALLY_SUSPENDED          = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 3600
  COMMENT = 'Dynamic Table refreshes for SHOPIFY_ANALYTICS';

-- 1. Generator: rebuild the UNION ALL Dynamic Tables from the registry ---------
CREATE OR REPLACE PROCEDURE SHOPIFY_RAW.META.REBUILD_ANALYTICS_DTS(
  p_target_lag VARCHAR DEFAULT '24 hours'
)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Regenerates SHOPIFY_ANALYTICS.CORE.*_ALL Dynamic Tables as UNION ALL over every active store schema.'
EXECUTE AS CALLER
AS
$$
DECLARE
  v_stores  RESULTSET;
  v_orders  VARCHAR DEFAULT '';
  v_items   VARCHAR DEFAULT '';
  v_fulfil  VARCHAR DEFAULT '';
  v_fo      VARCHAR DEFAULT '';
  v_sep     VARCHAR DEFAULT '';
  v_n       INTEGER DEFAULT 0;
BEGIN
  v_stores := (SELECT store_key FROM SHOPIFY_RAW.META.STORE_REGISTRY WHERE is_active ORDER BY store_key);

  FOR rec IN v_stores DO
    v_n := v_n + 1;

    v_orders := :v_orders || :v_sep ||
      'SELECT ''' || rec.store_key || ''' AS store_key, shop_url, id AS order_id, order_name, ' ||
      'created_at, updated_at, processed_at, cancelled_at, financial_status, fulfillment_status, ' ||
      'currency_code, is_test, customer_id, total_price, subtotal_price, total_tax, total_shipping, ' ||
      'total_discounts, total_refunded, ship_country, ship_province, ' ||
      '__snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || rec.store_key || '.ORDERS';

    v_items := :v_items || :v_sep ||
      'SELECT ''' || rec.store_key || ''' AS store_key, shop_url, id AS line_item_id, ' ||
      '__parent_id AS order_gid, title, sku, vendor, quantity, current_quantity, product_id, ' ||
      'variant_id, unit_price, discounted_total, __snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || rec.store_key || '.ORDER_LINE_ITEMS';

    v_fulfil := :v_fulfil || :v_sep ||
      'SELECT ''' || rec.store_key || ''' AS store_key, shop_url, id AS fulfillment_id, ' ||
      '__parent_id AS order_gid, status, created_at, updated_at, delivered_at, ' ||
      'estimated_delivery_at, tracking_company, tracking_number, ' ||
      '__snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || rec.store_key || '.ORDER_FULFILLMENTS';

    v_fo := :v_fo || :v_sep ||
      'SELECT ''' || rec.store_key || ''' AS store_key, shop_url, id AS fulfillment_order_id, ' ||
      'order_id, created_at, updated_at, status, request_status, fulfill_by, location_name, ' ||
      'location_id, delivery_method, __snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || rec.store_key || '.FULFILLMENT_ORDERS';

    v_sep := ' UNION ALL ';
  END FOR;

  IF (:v_n = 0) THEN
    RETURN 'ERROR: no active stores in STORE_REGISTRY. Fix: CALL ADD_STORE(...) first.';
  END IF;

  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.ORDERS_ALL ' ||
    'TARGET_LAG = ''' || :p_target_lag || ''' WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Orders from all active stores; generated by REBUILD_ANALYTICS_DTS'' AS ' || :v_orders;

  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.ORDER_LINE_ITEMS_ALL ' ||
    'TARGET_LAG = DOWNSTREAM WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Order line items from all active stores; generated'' AS ' || :v_items;

  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.ORDER_FULFILLMENTS_ALL ' ||
    'TARGET_LAG = DOWNSTREAM WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Shipments and fulfillments from all active stores; generated'' AS ' || :v_fulfil;

  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.FULFILLMENT_ORDERS_ALL ' ||
    'TARGET_LAG = DOWNSTREAM WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Fulfillment orders from all active stores; generated'' AS ' || :v_fo;

  RETURN 'OK: rebuilt 4 Dynamic Tables over ' || :v_n || ' stores with TARGET_LAG ' || :p_target_lag;
END;
$$;

CALL SHOPIFY_RAW.META.REBUILD_ANALYTICS_DTS('24 hours');

-- 2. Daily shop activity: one row per store per day ----------------------------
--    Hand-written (not generated) because it reads the *_ALL tables, which
--    already carry every store. TARGET_LAG DOWNSTREAM so it refreshes when
--    ORDERS_ALL does.
CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.DAILY_SHOP_ACTIVITY
  TARGET_LAG   = DOWNSTREAM
  WAREHOUSE    = SHOPIFY_ANALYTICS_WH
  REFRESH_MODE = AUTO
  COMMENT      = 'Per-store daily sales and shipment counts. Excludes test and soft-deleted orders.'
AS
WITH orders AS (
  SELECT store_key, shop_url, order_id, currency_code,
         CAST(CONVERT_TIMEZONE('UTC', processed_at) AS DATE) AS activity_date,
         total_price, total_discounts, total_refunded, cancelled_at
  FROM SHOPIFY_ANALYTICS.CORE.ORDERS_ALL
  WHERE NOT is_deleted
    AND NOT COALESCE(is_test, FALSE)
    AND processed_at IS NOT NULL
),
order_day AS (
  SELECT store_key, shop_url, activity_date, currency_code,
         COUNT(*)                                            AS orders_placed,
         COUNT_IF(cancelled_at IS NOT NULL)                  AS orders_cancelled,
         SUM(total_price)                                    AS gross_sales,
         SUM(total_discounts)                                AS discounts,
         SUM(total_refunded)                                 AS refunds,
         SUM(total_price) - SUM(total_refunded)              AS net_sales
  FROM orders
  GROUP BY store_key, shop_url, activity_date, currency_code
),
ship_day AS (
  SELECT store_key, shop_url,
         CAST(CONVERT_TIMEZONE('UTC', created_at) AS DATE)   AS activity_date,
         COUNT(*)                                            AS shipments_created,
         COUNT_IF(status = 'SUCCESS')                        AS shipments_success,
         COUNT_IF(delivered_at IS NOT NULL)                  AS shipments_delivered
  FROM SHOPIFY_ANALYTICS.CORE.ORDER_FULFILLMENTS_ALL
  WHERE NOT is_deleted
  GROUP BY store_key, shop_url, activity_date
),
units_day AS (
  SELECT o.store_key, o.activity_date,
         SUM(li.quantity) AS units_sold
  FROM orders o
  JOIN SHOPIFY_ANALYTICS.CORE.ORDER_LINE_ITEMS_ALL li
    ON li.store_key = o.store_key
   AND li.order_gid = 'gid://shopify/Order/' || o.order_id
  WHERE NOT li.is_deleted
  GROUP BY o.store_key, o.activity_date
)
SELECT
  COALESCE(od.store_key, sd.store_key)         AS store_key,
  COALESCE(od.shop_url, sd.shop_url)           AS shop_url,
  COALESCE(od.activity_date, sd.activity_date) AS activity_date,
  od.currency_code,
  COALESCE(od.orders_placed, 0)                AS orders_placed,
  COALESCE(od.orders_cancelled, 0)             AS orders_cancelled,
  COALESCE(ud.units_sold, 0)                   AS units_sold,
  od.gross_sales,
  od.discounts,
  od.refunds,
  od.net_sales,
  COALESCE(sd.shipments_created, 0)            AS shipments_created,
  COALESCE(sd.shipments_success, 0)            AS shipments_success,
  COALESCE(sd.shipments_delivered, 0)          AS shipments_delivered
FROM order_day od
FULL OUTER JOIN ship_day sd
  ON sd.store_key = od.store_key AND sd.activity_date = od.activity_date
LEFT JOIN units_day ud
  ON ud.store_key = COALESCE(od.store_key, sd.store_key)
 AND ud.activity_date = COALESCE(od.activity_date, sd.activity_date);

-- 3. Ops view: is every store still landing data? -----------------------------
CREATE OR REPLACE VIEW SHOPIFY_ANALYTICS.CORE.STORE_FRESHNESS
COMMENT = 'Hours since the newest order UPDATED_AT per store; registry stores with no rows show NULL'
AS
SELECT
  r.store_key,
  r.shop_domain,
  r.business_owner,
  r.connector_installed_at,
  MAX(o.updated_at)                                                  AS last_order_update,
  DATEDIFF('hour', MAX(o.updated_at), CURRENT_TIMESTAMP())           AS hours_since_last_update,
  COUNT(o.order_id)                                                  AS orders_loaded
FROM SHOPIFY_RAW.META.STORE_REGISTRY r
LEFT JOIN SHOPIFY_ANALYTICS.CORE.ORDERS_ALL o
  ON o.store_key = r.store_key
WHERE r.is_active
GROUP BY r.store_key, r.shop_domain, r.business_owner, r.connector_installed_at;

-- 4. Read access for analysts --------------------------------------------------
CREATE ROLE IF NOT EXISTS SHOPIFY_ANALYST
  COMMENT = 'Read-only access to SHOPIFY_ANALYTICS';
GRANT USAGE ON DATABASE SHOPIFY_ANALYTICS TO ROLE SHOPIFY_ANALYST;
GRANT USAGE ON SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT USAGE ON WAREHOUSE SHOPIFY_ANALYTICS_WH TO ROLE SHOPIFY_ANALYST;

-- 5. Verify -------------------------------------------------------------------
SELECT name, target_lag, scheduling_state, data_timestamp
FROM TABLE(SHOPIFY_ANALYTICS.INFORMATION_SCHEMA.DYNAMIC_TABLES())
ORDER BY name;

SELECT store_key, activity_date, orders_placed, units_sold, net_sales, shipments_created
FROM SHOPIFY_ANALYTICS.CORE.DAILY_SHOP_ACTIVITY
ORDER BY activity_date DESC, store_key
LIMIT 50;
