/*==============================================================================
CLEANUP - OpenAI Data Engineering
Drops all demo objects in reverse dependency order.
==============================================================================*/

USE SCHEMA SNOWFLAKE_EXAMPLE.OPENAI_DATA_ENG;

-- Approach 3: Cortex enrichment (depends on Approach 2)
DROP DYNAMIC TABLE IF EXISTS DT_PII_SCAN;
DROP DYNAMIC TABLE IF EXISTS DT_BATCH_ENRICHED;
DROP DYNAMIC TABLE IF EXISTS DT_ENRICHED_COMPLETIONS;
DROP VIEW IF EXISTS V_ENRICHMENT_DASHBOARD;

-- Approach 2: Gold dynamic tables (depend on Silver)
DROP DYNAMIC TABLE IF EXISTS DT_BATCH_SUMMARY;
DROP DYNAMIC TABLE IF EXISTS DT_TOOL_CALL_ANALYTICS;
DROP DYNAMIC TABLE IF EXISTS DT_DAILY_TOKEN_SUMMARY;

-- Approach 2: Silver dynamic tables (depend on RAW)
DROP DYNAMIC TABLE IF EXISTS DT_USAGE_FLAT;
DROP DYNAMIC TABLE IF EXISTS DT_BATCH_OUTCOMES;
DROP DYNAMIC TABLE IF EXISTS DT_TOOL_CALLS;
DROP DYNAMIC TABLE IF EXISTS DT_COMPLETIONS;

-- Approach 1: Views
DROP VIEW IF EXISTS V_TOKEN_USAGE;
DROP VIEW IF EXISTS V_BATCH_RESULTS;
DROP VIEW IF EXISTS V_STRUCTURED_OUTPUTS;
DROP VIEW IF EXISTS V_TOOL_CALLS;
DROP VIEW IF EXISTS V_COMPLETIONS;

-- Base tables
DROP TABLE IF EXISTS RAW_USAGE_BUCKETS;
DROP TABLE IF EXISTS RAW_BATCH_OUTPUTS;
DROP TABLE IF EXISTS RAW_CHAT_COMPLETIONS;

-- Staging infrastructure
DROP STAGE IF EXISTS openai_raw_stage;
DROP FILE FORMAT IF EXISTS openai_jsonl_ff;
