USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_REST_API_COST;

CREATE OR REPLACE VIEW V_MODEL_COST_SUMMARY
  COMMENT = 'TOOL: Per-model REST API cost aggregation (Expires: 2026-04-22)'
AS
SELECT
    MODEL_NAME,
    COUNT(DISTINCT REQUEST_ID)  AS REQUEST_COUNT,
    SUM(INPUT_TOKENS)           AS TOTAL_INPUT_TOKENS,
    SUM(OUTPUT_TOKENS)          AS TOTAL_OUTPUT_TOKENS,
    SUM(TOKENS)                 AS TOTAL_TOKENS,
    SUM(TOTAL_COST_USD)         AS TOTAL_COST_USD,
    ROUND(
        SUM(TOTAL_COST_USD) / NULLIF(SUM(SUM(TOTAL_COST_USD)) OVER (), 0) * 100,
        2
    ) AS PCT_OF_TOTAL_COST
FROM V_API_USAGE_COSTED
GROUP BY MODEL_NAME;
