USE ROLE ACCOUNTADMIN;

DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.ORDERS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.PRODUCTS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.CUSTOMERS;
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB;
DROP WAREHOUSE IF EXISTS SFE_COCO_GOVERNANCE_GITHUB_WH;
