/******************************************************************************
 * DR Cost Agent - Access Grants
 * USAGE_VIEWER for ACCOUNT_USAGE access; PUBLIC for read-only access.
 ******************************************************************************/

-- ACCOUNT_USAGE access for DB_METADATA_V2 and REPLICATION_HISTORY views
USE ROLE ACCOUNTADMIN;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE SYSADMIN;

-- Object access for users
USE ROLE SYSADMIN;
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.DR_COST_AGENT TO ROLE PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_EXAMPLE.DR_COST_AGENT TO ROLE PUBLIC;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_EXAMPLE.DR_COST_AGENT TO ROLE PUBLIC;
GRANT USAGE ON PROCEDURE SNOWFLAKE_EXAMPLE.DR_COST_AGENT.COST_PROJECTION(
    STRING, STRING, STRING, FLOAT, FLOAT, FLOAT
) TO ROLE PUBLIC;
GRANT USAGE ON PROCEDURE SNOWFLAKE_EXAMPLE.DR_COST_AGENT.UPDATE_PRICING(
    STRING, STRING, STRING, FLOAT
) TO ROLE SYSADMIN;

-- Semantic view access
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS TO ROLE PUBLIC;
GRANT SELECT ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_DR_COST TO ROLE PUBLIC;

-- Agent access
GRANT USAGE ON AGENT SNOWFLAKE_EXAMPLE.DR_COST_AGENT.DR_COST_AGENT TO ROLE PUBLIC;

-- Warehouse access
GRANT USAGE ON WAREHOUSE SFE_TOOLS_WH TO ROLE PUBLIC;
