USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_AGENT_COST;

CREATE OR REPLACE VIEW V_API_USAGE_COSTED
  COMMENT = 'TOOL: REST API usage with dollar cost per request (Expires: 2026-04-22)'
AS
WITH rated AS (
    SELECT
        u.START_TIME,
        u.REQUEST_ID,
        u.MODEL_NAME,
        u.TOKENS,
        u.INPUT_TOKENS,
        u.OUTPUT_TOKENS,
        u.USER_ID,
        u.INFERENCE_REGION,
        COALESCE(p_global.INPUT_USD_PER_MTOK,  p_default.INPUT_USD_PER_MTOK)  AS INPUT_RATE,
        COALESCE(p_global.OUTPUT_USD_PER_MTOK, p_default.OUTPUT_USD_PER_MTOK) AS OUTPUT_RATE
    FROM V_API_USAGE_DETAIL u
    LEFT JOIN CORTEX_API_PRICING p_global
      ON u.MODEL_NAME = p_global.MODEL_NAME
      AND p_global.REGION_CATEGORY = 'GLOBAL'
      AND (u.INFERENCE_REGION ILIKE '%GLOBAL%' OR u.INFERENCE_REGION ILIKE '%CROSS%')
    LEFT JOIN CORTEX_API_PRICING p_default
      ON u.MODEL_NAME = p_default.MODEL_NAME
      AND p_default.REGION_CATEGORY = 'DEFAULT'
)
SELECT
    START_TIME,
    REQUEST_ID,
    MODEL_NAME,
    TOKENS,
    INPUT_TOKENS,
    OUTPUT_TOKENS,
    USER_ID,
    INFERENCE_REGION,
    INPUT_RATE,
    OUTPUT_RATE,
    ROUND(COALESCE(INPUT_TOKENS, 0)  * COALESCE(INPUT_RATE, 0)  / 1000000, 6) AS INPUT_COST_USD,
    ROUND(COALESCE(OUTPUT_TOKENS, 0) * COALESCE(OUTPUT_RATE, 0) / 1000000, 6) AS OUTPUT_COST_USD,
    ROUND(COALESCE(INPUT_TOKENS, 0)  * COALESCE(INPUT_RATE, 0)  / 1000000, 6)
      + ROUND(COALESCE(OUTPUT_TOKENS, 0) * COALESCE(OUTPUT_RATE, 0) / 1000000, 6) AS TOTAL_COST_USD
FROM rated;
