USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_AGENT_COST;

CREATE OR REPLACE VIEW V_DAILY_COST_SUMMARY
  COMMENT = 'TOOL: Daily REST API cost aggregation (Expires: 2026-04-22)'
AS
SELECT
    START_TIME::DATE            AS USAGE_DATE,
    COUNT(DISTINCT REQUEST_ID)  AS REQUEST_COUNT,
    SUM(INPUT_TOKENS)           AS TOTAL_INPUT_TOKENS,
    SUM(OUTPUT_TOKENS)          AS TOTAL_OUTPUT_TOKENS,
    SUM(TOKENS)                 AS TOTAL_TOKENS,
    SUM(TOTAL_COST_USD)         AS TOTAL_COST_USD
FROM V_API_USAGE_COSTED
GROUP BY USAGE_DATE;
