USE DATABASE SNOWFLAKE_EXAMPLE;
USE SCHEMA IOT_LIFECYCLE;
USE WAREHOUSE SFE_IOT_LIFECYCLE_WH;

CREATE TRANSIENT TABLE IF NOT EXISTS FLEET_VEHICLES (
    VEHICLE_ID      VARCHAR(10)   NOT NULL,
    LICENSE_PLATE   VARCHAR(10)   NOT NULL,
    DRIVER_NAME     VARCHAR(50)   NOT NULL,
    VEHICLE_TYPE    VARCHAR(20)   NOT NULL,
    CAPACITY_LBS    NUMBER(8,0)   NOT NULL,
    HOME_DEPOT      VARCHAR(30)   NOT NULL,
    STATUS          VARCHAR(15)   DEFAULT 'ACTIVE'
) COMMENT = 'DEMO: Fleet vehicle registry (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID             VARCHAR(10)   NOT NULL,
    CUSTOMER_NAME           VARCHAR(80)   NOT NULL,
    INDUSTRY                VARCHAR(30)   NOT NULL,
    ADDRESS                 VARCHAR(120),
    CITY                    VARCHAR(40)   NOT NULL,
    STATE                   VARCHAR(2)    DEFAULT 'GA',
    LATITUDE                FLOAT         NOT NULL,
    LONGITUDE               FLOAT         NOT NULL,
    CONTRACT_TYPE           VARCHAR(20)   DEFAULT 'WEEKLY',
    MONTHLY_VALUE           NUMBER(10,2),
    ROUTE_ID                VARCHAR(10),
    CSAT_SCORE              NUMBER(3,1),
    INVOICE_DISPUTE_COUNT   NUMBER(4,0)   DEFAULT 0,
    RETURN_RATE_PCT         NUMBER(5,2)   DEFAULT 100.00
) COMMENT = 'DEMO: Customer locations across Atlanta metro (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS ROUTES (
    ROUTE_ID            VARCHAR(10)   NOT NULL,
    ROUTE_NAME          VARCHAR(40)   NOT NULL,
    VEHICLE_ID          VARCHAR(10)   NOT NULL,
    DAY_OF_WEEK         VARCHAR(10)   NOT NULL,
    STOP_COUNT          NUMBER(3,0),
    ESTIMATED_MILES     NUMBER(6,1),
    FUEL_COST_USD       NUMBER(8,2),
    AVG_FUEL_COST_USD   NUMBER(8,2)
) COMMENT = 'DEMO: Daily delivery routes (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS GPS_TELEMETRY (
    TELEMETRY_ID    NUMBER(10,0)  IDENTITY START 1 INCREMENT 1,
    VEHICLE_ID      VARCHAR(10)   NOT NULL,
    TIMESTAMP       TIMESTAMP_NTZ NOT NULL,
    LATITUDE        FLOAT         NOT NULL,
    LONGITUDE       FLOAT         NOT NULL,
    SPEED_MPH       NUMBER(5,1)   DEFAULT 0,
    HEADING         NUMBER(5,1),
    ENGINE_STATUS   VARCHAR(10)   DEFAULT 'ON'
) COMMENT = 'DEMO: Vehicle GPS telemetry -- positions every 5 min (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS GARMENTS (
    GARMENT_ID          VARCHAR(15)   NOT NULL,
    RFID_TAG            VARCHAR(24)   NOT NULL,
    GARMENT_TYPE        VARCHAR(30)   NOT NULL,
    SIZE                VARCHAR(5),
    COLOR               VARCHAR(15),
    CUSTOMER_ID         VARCHAR(10),
    ASSIGNED_DATE       DATE,
    STATUS              VARCHAR(15)   DEFAULT 'IN_SERVICE',
    WASH_COUNT          NUMBER(6,0)   DEFAULT 0,
    USEFUL_LIFE_CYCLES  NUMBER(4,0)   DEFAULT 100,
    REPLACEMENT_COST    NUMBER(8,2),
    DAYS_AT_LOCATION    NUMBER(4,0)   DEFAULT 0,
    LIFECYCLE_STATE     VARCHAR(20)   DEFAULT 'IN_PLANT'
) COMMENT = 'DEMO: RFID-tagged garment inventory (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS GARMENT_EVENTS (
    EVENT_ID        NUMBER(10,0)  IDENTITY START 1 INCREMENT 1,
    GARMENT_ID      VARCHAR(15)   NOT NULL,
    EVENT_TYPE      VARCHAR(20)   NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    LOCATION        VARCHAR(40),
    SCANNER_ID      VARCHAR(15),
    NOTES           VARCHAR(200)
) COMMENT = 'DEMO: RFID garment lifecycle events (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS INVOICES (
    INVOICE_ID      VARCHAR(15)   NOT NULL,
    CUSTOMER_ID     VARCHAR(10)   NOT NULL,
    INVOICE_DATE    DATE          NOT NULL,
    DUE_DATE        DATE          NOT NULL,
    TOTAL_AMOUNT    NUMBER(12,2)  NOT NULL,
    PAYMENT_STATUS  VARCHAR(15)   DEFAULT 'PENDING',
    PAID_DATE       DATE
) COMMENT = 'DEMO: Customer invoices (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS INVOICE_LINE_ITEMS (
    LINE_ID         NUMBER(10,0)  IDENTITY START 1 INCREMENT 1,
    INVOICE_ID      VARCHAR(15)   NOT NULL,
    SERVICE_TYPE    VARCHAR(30)   NOT NULL,
    QUANTITY        NUMBER(8,0)   NOT NULL,
    UNIT_PRICE      NUMBER(8,2)   NOT NULL,
    LINE_TOTAL      NUMBER(12,2)  NOT NULL
) COMMENT = 'DEMO: Invoice line items by service type (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS GL_CODES (
    GL_CODE         VARCHAR(10)   NOT NULL,
    GL_NAME         VARCHAR(60)   NOT NULL,
    GL_CATEGORY     VARCHAR(30)   NOT NULL,
    GL_TYPE         VARCHAR(15)   NOT NULL
) COMMENT = 'DEMO: General ledger code taxonomy (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS FINANCIAL_ACTUALS (
    PERIOD_ID       VARCHAR(10)   NOT NULL,
    FISCAL_YEAR     NUMBER(4,0)   NOT NULL,
    FISCAL_QUARTER  VARCHAR(2)    NOT NULL,
    FISCAL_MONTH    DATE          NOT NULL,
    GL_CODE         VARCHAR(10)   NOT NULL,
    AMOUNT          NUMBER(14,2)  NOT NULL
) COMMENT = 'DEMO: Monthly P&L actuals by GL code (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS FINANCIAL_BUDGET (
    PERIOD_ID       VARCHAR(10)   NOT NULL,
    FISCAL_YEAR     NUMBER(4,0)   NOT NULL,
    FISCAL_QUARTER  VARCHAR(2)    NOT NULL,
    FISCAL_MONTH    DATE          NOT NULL,
    GL_CODE         VARCHAR(10)   NOT NULL,
    BUDGET_AMOUNT   NUMBER(14,2)  NOT NULL
) COMMENT = 'DEMO: Monthly budget by GL code for variance analysis (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS GARMENT_COSTS (
    GARMENT_TYPE            VARCHAR(30)   NOT NULL,
    REPLACEMENT_COST        NUMBER(8,2)   NOT NULL,
    AVG_LAUNDERING_COST_LB  NUMBER(6,2)   NOT NULL,
    USEFUL_LIFE_CYCLES      NUMBER(4,0)   NOT NULL
) COMMENT = 'DEMO: Garment replacement/maintenance cost benchmarks (Expires: 2026-06-11)';

CREATE TRANSIENT TABLE IF NOT EXISTS RETENTION_ALERTS (
    ALERT_ID            VARCHAR(15)   NOT NULL,
    CUSTOMER_ID         VARCHAR(10)   NOT NULL,
    ALERT_DATE          DATE          NOT NULL,
    MISSING_TAG_COUNT   NUMBER(6,0)   NOT NULL,
    FINANCIAL_SAVE_USD  NUMBER(10,2)  NOT NULL,
    DRIVER_TALKING_POINT VARCHAR(500) NOT NULL,
    STATUS              VARCHAR(15)   DEFAULT 'PENDING'
) COMMENT = 'DEMO: Retention alerts for route drivers (Expires: 2026-06-11)';
