/*==============================================================================
TEARDOWN - Cortex Financial Agents
WARNING: This will DELETE all project objects. Cannot be undone.
==============================================================================*/

-- Remove agent from Snowflake Intelligence before dropping
USE ROLE ACCOUNTADMIN;
ALTER SNOWFLAKE INTELLIGENCE IF EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
  DROP AGENT SNOWFLAKE_EXAMPLE.FINANCIAL_AGENTS.PORTFOLIO_RISK_AGENT;

USE ROLE SYSADMIN;

DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.FINANCIAL_AGENTS.PORTFOLIO_RISK_AGENT;
DROP CORTEX SEARCH SERVICE IF EXISTS SNOWFLAKE_EXAMPLE.FINANCIAL_AGENTS.FACILITY_DOCUMENT_SEARCH;
DROP STAGE IF EXISTS SNOWFLAKE_EXAMPLE.FINANCIAL_AGENTS.DOC_STAGE;
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_FINANCIAL_PORTFOLIO;
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.FINANCIAL_AGENTS CASCADE;
DROP WAREHOUSE IF EXISTS SFE_FINANCIAL_AGENTS_WH;

-- PROTECTED - NEVER DROP:
-- SNOWFLAKE_EXAMPLE database
-- SNOWFLAKE_EXAMPLE.GIT_REPOS schema
-- SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS schema
-- SFE_GIT_API_INTEGRATION

SELECT 'Teardown complete!' AS status;
