/*=============================================================================
  03_processing/02_create_consumer.sql
  Snowflake Streams CDC Workshop - Transactional CDC Consumer
  Pair-programmed by SE Community + Cortex Code | Expires: 2026-10-08
=============================================================================*/

USE ROLE SYSADMIN;
USE WAREHOUSE SFE_STREAMS_CDC_WH;
USE SCHEMA SNOWFLAKE_EXAMPLE.STREAMS_CDC_WORKSHOP;

CREATE OR REPLACE PROCEDURE SP_CONSUME_ORDER_CHANGES()
  RETURNS VARCHAR
  LANGUAGE SQL
  COMMENT = 'DEMO: Atomically audits and applies one Stream snapshot (Expires: 2026-10-08)'
  EXECUTE AS OWNER
AS
$$
DECLARE
  BATCH_ID VARCHAR DEFAULT UUID_STRING();
  AUDIT_ROW_COUNT NUMBER DEFAULT 0;
BEGIN
  BEGIN TRANSACTION;

  INSERT INTO ORDER_CHANGE_AUDIT (
    BATCH_ID,
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_TOTAL,
    ORDER_TS,
    UPDATED_AT,
    CDC_ACTION,
    CDC_IS_UPDATE,
    CDC_ROW_ID,
    PROCESSED_AT
  )
  SELECT
    :BATCH_ID,
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_TOTAL,
    ORDER_TS,
    UPDATED_AT,
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID,
    CURRENT_TIMESTAMP()
  FROM RAW_ORDERS_STREAM;

  AUDIT_ROW_COUNT := SQLROWCOUNT;

  MERGE INTO CURRENT_ORDERS AS TARGET
  USING (
    SELECT
      ORDER_ID,
      CUSTOMER_ID,
      ORDER_STATUS,
      ORDER_TOTAL,
      ORDER_TS,
      UPDATED_AT,
      METADATA$ACTION AS CDC_ACTION,
      METADATA$ISUPDATE AS CDC_IS_UPDATE
    FROM RAW_ORDERS_STREAM
  ) AS SOURCE
    ON TARGET.ORDER_ID = SOURCE.ORDER_ID
  WHEN MATCHED
    AND SOURCE.CDC_ACTION = 'DELETE'
    AND NOT SOURCE.CDC_IS_UPDATE
    THEN DELETE
  WHEN MATCHED
    AND SOURCE.CDC_ACTION = 'INSERT'
    THEN UPDATE SET
      TARGET.CUSTOMER_ID = SOURCE.CUSTOMER_ID,
      TARGET.ORDER_STATUS = SOURCE.ORDER_STATUS,
      TARGET.ORDER_TOTAL = SOURCE.ORDER_TOTAL,
      TARGET.ORDER_TS = SOURCE.ORDER_TS,
      TARGET.UPDATED_AT = SOURCE.UPDATED_AT,
      TARGET.CDC_APPLIED_AT = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED
    AND SOURCE.CDC_ACTION = 'INSERT'
    THEN INSERT (
      ORDER_ID,
      CUSTOMER_ID,
      ORDER_STATUS,
      ORDER_TOTAL,
      ORDER_TS,
      UPDATED_AT,
      CDC_APPLIED_AT
    )
    VALUES (
      SOURCE.ORDER_ID,
      SOURCE.CUSTOMER_ID,
      SOURCE.ORDER_STATUS,
      SOURCE.ORDER_TOTAL,
      SOURCE.ORDER_TS,
      SOURCE.UPDATED_AT,
      CURRENT_TIMESTAMP()
    );

  COMMIT;
  RETURN 'SUCCESS: batch ' || :BATCH_ID || ' committed ' || :AUDIT_ROW_COUNT || ' CDC rows.';
EXCEPTION
  WHEN OTHER THEN
    ROLLBACK;
    RAISE;
END;
$$;
