USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS SNOWFLAKE_EXAMPLE
    COMMENT = 'DEMO: Repository for example/demo projects - NOT FOR PRODUCTION (Expires: 2026-04-15)';

CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB
    COMMENT = 'DEMO: coco-governance-github - Governed GitHub MCP integration for Cortex Code (Expires: 2026-04-15)';

CREATE WAREHOUSE IF NOT EXISTS SFE_COCO_GOVERNANCE_GITHUB_WH WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'DEMO: coco-governance-github - Compute for governance advisor queries (Expires: 2026-04-15)';

USE DATABASE SNOWFLAKE_EXAMPLE;
USE SCHEMA COCO_GOVERNANCE_GITHUB;
USE WAREHOUSE SFE_COCO_GOVERNANCE_GITHUB_WH;
