USE SCHEMA SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB;
USE WAREHOUSE SFE_COCO_GOVERNANCE_GITHUB_WH;

CREATE TABLE IF NOT EXISTS GOVERNANCE_POLICY_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    LOGGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    POLICY_TYPE VARCHAR(50) NOT NULL,
    POLICY_HASH VARCHAR(64),
    DEPLOYER VARCHAR(100),
    PLATFORM VARCHAR(20),
    POLICY_SUMMARY VARIANT,
    VALIDATION_RESULT VARCHAR(20),
    NOTES VARCHAR(500)
)
COMMENT = 'DEMO: coco-governance-github - Tracks governance policy deployment events (Expires: 2026-04-15)';

CREATE TABLE IF NOT EXISTS MCP_CONNECTION_AUDIT (
    AUDIT_ID NUMBER AUTOINCREMENT,
    AUDITED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SERVER_NAME VARCHAR(100) NOT NULL,
    AUTH_METHOD VARCHAR(50),
    TOOLSETS_ENABLED VARIANT,
    TOOLSET_PROFILE VARCHAR(20),
    GOVERNANCE_VALIDATED BOOLEAN DEFAULT FALSE,
    VALIDATION_DETAILS VARIANT,
    NOTES VARCHAR(500),
    COMMENT = 'DEMO: coco-governance-github - Tracks MCP connection configurations (Expires: 2026-04-15)'
);

INSERT INTO GOVERNANCE_POLICY_LOG (POLICY_TYPE, DEPLOYER, PLATFORM, POLICY_SUMMARY, VALIDATION_RESULT, NOTES)
SELECT
    'managed-settings.json',
    'demo-setup',
    'demo',
    PARSE_JSON('{
        "version": "1.0",
        "permissions": {"dangerouslyAllowAll": false},
        "settings": {"forceSandboxEnabled": true},
        "ui": {"showManagedBanner": true}
    }'),
    'PASS',
    'Sample governance policy from demo deployment';

INSERT INTO MCP_CONNECTION_AUDIT (SERVER_NAME, AUTH_METHOD, TOOLSETS_ENABLED, TOOLSET_PROFILE, GOVERNANCE_VALIDATED, NOTES)
SELECT
    'github',
    '1password',
    PARSE_JSON('["repos", "issues"]'),
    'standard',
    TRUE,
    'Sample GitHub MCP connection after governance validation';
