USE SCHEMA SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB;
USE WAREHOUSE SFE_COCO_GOVERNANCE_GITHUB_WH;

CREATE OR REPLACE FUNCTION VALIDATE_GOVERNANCE_POLICY(CHECK_TYPE VARCHAR)
RETURNS VARIANT
LANGUAGE SQL
COMMENT = 'DEMO: coco-governance-github - Validates governance readiness for MCP connections (Expires: 2026-04-15)'
AS
$$
    SELECT OBJECT_CONSTRUCT(
        'check_type', CHECK_TYPE,
        'checked_at', CURRENT_TIMESTAMP()::VARCHAR,
        'governance_policies_deployed', (
            SELECT COUNT(*)
            FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.GOVERNANCE_POLICY_LOG
            WHERE VALIDATION_RESULT = 'PASS'
        ),
        'latest_policy_date', (
            SELECT MAX(LOGGED_AT)::VARCHAR
            FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.GOVERNANCE_POLICY_LOG
            WHERE VALIDATION_RESULT = 'PASS'
        ),
        'mcp_connections_configured', (
            SELECT COUNT(*)
            FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.MCP_CONNECTION_AUDIT
            WHERE GOVERNANCE_VALIDATED = TRUE
        ),
        'readiness', CASE
            WHEN (SELECT COUNT(*) FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.GOVERNANCE_POLICY_LOG WHERE VALIDATION_RESULT = 'PASS') > 0
                AND CHECK_TYPE = 'full'
                AND (SELECT COUNT(*) FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.MCP_CONNECTION_AUDIT WHERE GOVERNANCE_VALIDATED = TRUE) > 0
            THEN 'READY - Governance deployed and MCP validated'
            WHEN (SELECT COUNT(*) FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.GOVERNANCE_POLICY_LOG WHERE VALIDATION_RESULT = 'PASS') > 0
            THEN 'PARTIAL - Governance deployed, MCP not yet configured'
            ELSE 'NOT READY - No governance policy deployed'
        END,
        'next_steps', CASE
            WHEN (SELECT COUNT(*) FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.GOVERNANCE_POLICY_LOG WHERE VALIDATION_RESULT = 'PASS') = 0
            THEN 'Deploy managed-settings.json via MDM. See docs/02-GOVERNANCE-FIRST.md'
            WHEN (SELECT COUNT(*) FROM SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.MCP_CONNECTION_AUDIT WHERE GOVERNANCE_VALIDATED = TRUE) = 0
            THEN 'Configure GitHub MCP with governance validation. See docs/03-GITHUB-MCP-SETUP.md'
            ELSE 'Governance and MCP are configured. Review toolset scoping in docs/04-TOOLSET-SCOPING.md'
        END
    )
$$;
