from __future__ import annotations

import json
import re
import sys
from pathlib import Path


STORE_KEY = re.compile(r"^[A-Z][A-Z0-9_]{0,62}$")
SHOP_DOMAIN = re.compile(r"^[a-z0-9-]+\.myshopify\.com$")
FQN = re.compile(r"^[A-Z][A-Z0-9_$]*\.[A-Z][A-Z0-9_$]*\.[A-Z][A-Z0-9_$]*$")


def load_stores(path: Path) -> list[dict[str, str]]:
    stores = json.loads(path.read_text())
    if not isinstance(stores, list) or not stores:
        raise ValueError("stores.json must be a non-empty JSON array")
    seen_keys: set[str] = set()
    seen_domains: set[str] = set()
    for store in stores:
        key = store["store_key"].upper()
        domain = store["shop_domain"].lower()
        credential_object = store["credential_object_fqn"].upper()
        if not STORE_KEY.fullmatch(key):
            raise ValueError(f"Invalid store_key: {key}")
        if not SHOP_DOMAIN.fullmatch(domain):
            raise ValueError(f"Invalid shop_domain: {domain}")
        if not FQN.fullmatch(credential_object):
            raise ValueError(f"Invalid credential_object_fqn: {credential_object}")
        if key in seen_keys or domain in seen_domains:
            raise ValueError(f"Duplicate store: {key} / {domain}")
        store.update(
            store_key=key,
            shop_domain=domain,
            credential_object_fqn=credential_object,
        )
        seen_keys.add(key)
        seen_domains.add(domain)
    return stores


def render(stores: list[dict[str, str]]) -> str:
    aliases = [(f"store_{index:03d}", store) for index, store in enumerate(stores, 1)]
    eai_secrets = ",\n    ".join(
        store["credential_object_fqn"] for _, store in aliases
    )
    secret_clause = ",\n  ".join(
        f"'{alias}' = {store['credential_object_fqn']}" for alias, store in aliases
    )
    mapping = json.dumps(
        {
            store["store_key"]: {
                "domain": store["shop_domain"],
                "binding_alias": alias,
            }
            for alias, store in aliases
        },
        sort_keys=True,
    )
    registry_rows = ",\n  ".join(
        f"('{store['store_key']}', '{store['shop_domain']}', '{store['credential_object_fqn']}')"
        for _, store in aliases
    )
    secret_grants = "\n".join(
        f"GRANT READ ON SECRET {store['credential_object_fqn']} TO ROLE SHOPIFY_PIPELINE_RL;"
        for _, store in aliases
    )
    return f"""-- Generated by tools/generate_store_bindings.py. Do not edit.
CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS SHOPIFY_NATIVE_EAI
  ALLOWED_NETWORK_RULES = (SHOPIFY_NATIVE.CONTROL.SHOPIFY_API_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (
    {stores[0]['credential_object_fqn']}
  )
  ENABLED = TRUE
  COMMENT = 'Outbound access for the deterministic Shopify pull procedure';

ALTER EXTERNAL ACCESS INTEGRATION SHOPIFY_NATIVE_EAI
  SET ALLOWED_AUTHENTICATION_SECRETS = (
    {eai_secrets}
  );

GRANT USAGE ON INTEGRATION SHOPIFY_NATIVE_EAI TO ROLE SHOPIFY_PIPELINE_RL;
{secret_grants}

MERGE INTO SHOPIFY_NATIVE.CONTROL.STORE_REGISTRY AS target
USING (SELECT COLUMN1 STORE_KEY, COLUMN2 SHOP_DOMAIN, COLUMN3 CREDENTIAL_OBJECT_FQN FROM VALUES
  {registry_rows}
) AS source
ON target.STORE_KEY = source.STORE_KEY
WHEN MATCHED THEN UPDATE SET SHOP_DOMAIN = source.SHOP_DOMAIN,
  CREDENTIAL_OBJECT_FQN = source.CREDENTIAL_OBJECT_FQN
WHEN NOT MATCHED THEN INSERT (STORE_KEY, SHOP_DOMAIN, CREDENTIAL_OBJECT_FQN)
  VALUES (source.STORE_KEY, source.SHOP_DOMAIN, source.CREDENTIAL_OBJECT_FQN);

-- Paste these generated fragments into sql/03_pull_procedure.sql:
-- SECRETS = (
--   {secret_clause}
-- )
-- STORE_BINDINGS = {mapping}
"""


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("Usage: python tools/generate_store_bindings.py config/stores.json")
    print(render(load_stores(Path(sys.argv[1]))))
