USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AGENT_COST
  COMMENT = 'TOOL: Cortex Agent cost reporting and forecasting (Expires: 2026-04-22)';

CREATE WAREHOUSE IF NOT EXISTS SFE_CORTEX_AGENT_COST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'TOOL: Cortex Agent Cost compute (Expires: 2026-04-22)';

USE WAREHOUSE SFE_CORTEX_AGENT_COST_WH;
USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_AGENT_COST;
