USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_REST_API_COST;

CREATE OR REPLACE VIEW V_API_USAGE_DETAIL
  COMMENT = 'TOOL: Flattened REST API usage with input/output token breakdown (Expires: 2026-04-22)'
AS
SELECT
    START_TIME,
    END_TIME,
    REQUEST_ID,
    MODEL_NAME,
    TOKENS,
    TOKENS_GRANULAR:"input"::NUMBER  AS INPUT_TOKENS,
    TOKENS_GRANULAR:"output"::NUMBER AS OUTPUT_TOKENS,
    USER_ID,
    INFERENCE_REGION
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_REST_API_USAGE_HISTORY;
