DEFINE VIEW {{db}}.{{schema}}.DB_METADATA_V2
    COMMENT = 'TOOL: Database sizes with hybrid table exclusion for replication sizing (Expires: {{expiration_date}})'
AS
WITH ALL_DBS AS (
    SELECT DATABASE_NAME
    FROM {{db}}.INFORMATION_SCHEMA.DATABASES
    WHERE DATABASE_NAME NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'UTIL_DB')
),
DB_STORAGE AS (
    SELECT
        TABLE_CATALOG AS DATABASE_NAME,
        SUM(ACTIVE_BYTES) AS TOTAL_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE TABLE_CATALOG NOT IN ('SNOWFLAKE', 'SNOWFLAKE_SAMPLE_DATA', 'UTIL_DB')
      AND DELETED IS NULL
    GROUP BY TABLE_CATALOG
),
HYBRID_STORAGE AS (
    SELECT
        DATABASE_NAME,
        COUNT(*) AS HYBRID_TABLE_COUNT,
        COALESCE(SUM(BYTES), 0) AS HYBRID_TABLE_BYTES
    FROM SNOWFLAKE.ACCOUNT_USAGE.HYBRID_TABLES
    WHERE DELETED IS NULL
    GROUP BY DATABASE_NAME
)
SELECT
    d.DATABASE_NAME,
    COALESCE((s.TOTAL_BYTES / POWER(1024, 4)), 0)::NUMBER(18,6) AS TOTAL_SIZE_TB,
    COALESCE((h.HYBRID_TABLE_BYTES / POWER(1024, 4)), 0)::NUMBER(18,6) AS HYBRID_EXCLUDED_TB,
    (COALESCE((s.TOTAL_BYTES / POWER(1024, 4)), 0)
     - COALESCE((h.HYBRID_TABLE_BYTES / POWER(1024, 4)), 0))::NUMBER(18,6) AS REPLICABLE_SIZE_TB,
    COALESCE(h.HYBRID_TABLE_COUNT, 0) AS HYBRID_TABLE_COUNT,
    CASE WHEN COALESCE(h.HYBRID_TABLE_COUNT, 0) > 0 THEN TRUE ELSE FALSE END AS HAS_HYBRID_TABLES,
    CURRENT_TIMESTAMP() AS QUERIED_AT,
    -- ACCOUNT_USAGE views lag up to 3 hours; use latest catalog creation as a proxy
    DATEDIFF('hour',
        (SELECT MAX(CATALOG_CREATED) FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
         WHERE DELETED IS NULL),
        CURRENT_TIMESTAMP()
    ) AS DATA_STALENESS_HOURS
FROM ALL_DBS d
LEFT JOIN DB_STORAGE s ON d.DATABASE_NAME = s.DATABASE_NAME
LEFT JOIN HYBRID_STORAGE h ON d.DATABASE_NAME = h.DATABASE_NAME;


DEFINE VIEW {{db}}.{{schema}}.HYBRID_TABLE_METADATA
    COMMENT = 'TOOL: Hybrid table inventory per database -- excluded from replication (Expires: {{expiration_date}})'
AS
SELECT
    DATABASE_NAME,
    SCHEMA_NAME AS TABLE_SCHEMA,
    NAME AS TABLE_NAME,
    BYTES,
    (BYTES / POWER(1024, 3))::NUMBER(18,4) AS SIZE_GB,
    CREATED AS CREATED_AT,
    LAST_ALTERED AS LAST_ALTERED_AT,
    CURRENT_TIMESTAMP() AS AS_OF
FROM SNOWFLAKE.ACCOUNT_USAGE.HYBRID_TABLES
WHERE DELETED IS NULL;


DEFINE VIEW {{db}}.{{schema}}.REPLICATION_HISTORY
    COMMENT = 'TOOL: Actual replication costs from ACCOUNT_USAGE (Expires: {{expiration_date}})'
AS
SELECT
    REPLICATION_GROUP_NAME,
    REPLICATION_GROUP_ID,
    START_TIME,
    END_TIME,
    DATE_TRUNC('day', START_TIME)::DATE AS USAGE_DATE,
    DATE_TRUNC('month', START_TIME)::DATE AS USAGE_MONTH,
    CREDITS_USED,
    BYTES_TRANSFERRED,
    (BYTES_TRANSFERRED / POWER(1024, 4))::NUMBER(18,6) AS TB_TRANSFERRED
FROM SNOWFLAKE.ACCOUNT_USAGE.REPLICATION_GROUP_USAGE_HISTORY;
