USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS SNOWFLAKE_EXAMPLE.CORTEX_REST_API_COST
  COMMENT = 'TOOL: Cortex REST API cost reporting (Expires: 2026-04-22)';

CREATE WAREHOUSE IF NOT EXISTS SFE_CORTEX_REST_API_COST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'TOOL: Cortex REST API Cost compute (Expires: 2026-04-22)';

USE WAREHOUSE SFE_CORTEX_REST_API_COST_WH;
USE SCHEMA SNOWFLAKE_EXAMPLE.CORTEX_REST_API_COST;
