/* Shopify Bulk API + CoCo — landing layer
   Pair-programmed by SE Community + Cortex Code
   Expires: 2026-12-03 */

USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS SHOPIFY_PIPELINE_RL
  COMMENT = 'Owns the deterministic Shopify ingestion pipeline';
GRANT ROLE SHOPIFY_PIPELINE_RL TO ROLE SYSADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SHOPIFY_PIPELINE_RL;

CREATE DATABASE IF NOT EXISTS SHOPIFY_NATIVE;
CREATE SCHEMA IF NOT EXISTS SHOPIFY_NATIVE.CONTROL;
CREATE SCHEMA IF NOT EXISTS SHOPIFY_NATIVE.LANDING;
CREATE SCHEMA IF NOT EXISTS SHOPIFY_NATIVE.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS SHOPIFY_PIPELINE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 7200
  COMMENT = 'Daily Shopify Bulk API pull, COPY, and Dynamic Table refresh';

GRANT USAGE, OPERATE ON WAREHOUSE SHOPIFY_PIPELINE_WH TO ROLE SHOPIFY_PIPELINE_RL;

GRANT OWNERSHIP ON DATABASE SHOPIFY_NATIVE TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SHOPIFY_NATIVE.CONTROL TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SHOPIFY_NATIVE.LANDING TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SHOPIFY_NATIVE.ANALYTICS TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;

USE ROLE SHOPIFY_PIPELINE_RL;
CREATE STAGE IF NOT EXISTS SHOPIFY_NATIVE.LANDING.SHOPIFY_STAGE
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Immutable JSONL results from Shopify Bulk Operations';

CREATE FILE FORMAT IF NOT EXISTS SHOPIFY_NATIVE.LANDING.JSONL_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.CONTROL.STORE_REGISTRY (
  STORE_KEY VARCHAR(64) NOT NULL,
  SHOP_DOMAIN VARCHAR(255) NOT NULL,
  CREDENTIAL_OBJECT_FQN VARCHAR(255) NOT NULL,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
  QUALIFICATION_STATUS VARCHAR(32) NOT NULL DEFAULT 'NOT_RUN',
  LAST_QUALIFIED_AT TIMESTAMP_TZ,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_STORE_REGISTRY PRIMARY KEY (STORE_KEY),
  CONSTRAINT UQ_STORE_DOMAIN UNIQUE (SHOP_DOMAIN)
);

CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.CONTROL.PULL_RUN_LOG (
  RUN_ID VARCHAR(36) NOT NULL,
  STORE_KEY VARCHAR(64) NOT NULL,
  OBJECT_NAME VARCHAR(64) NOT NULL,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT TIMESTAMP_TZ,
  STATUS VARCHAR(32) NOT NULL,
  BULK_OPERATION_ID VARCHAR,
  FILE_NAME VARCHAR,
  OBJECT_COUNT NUMBER,
  ROWS_LOADED NUMBER,
  WATERMARK_FROM TIMESTAMP_TZ,
  WATERMARK_TO TIMESTAMP_TZ,
  ERROR_CLASS VARCHAR,
  ERROR_MESSAGE VARCHAR,
  QUERY_ID VARCHAR
);

CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.CONTROL.QUALIFICATION_RESULTS (
  STORE_KEY VARCHAR(64) NOT NULL,
  GATE_NAME VARCHAR(64) NOT NULL,
  PASSED BOOLEAN NOT NULL,
  EVIDENCE VARIANT,
  CHECKED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW (
  STORE_KEY VARCHAR(64) NOT NULL,
  OBJECT_NAME VARCHAR(64) NOT NULL,
  PULLED_AT TIMESTAMP_TZ NOT NULL,
  SOURCE_FILE VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER NOT NULL,
  RECORD VARIANT NOT NULL,
  LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE;

CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.CONTROL.RECONCILIATION_BASELINE (
  STORE_KEY VARCHAR(64) NOT NULL,
  ACTIVITY_DATE DATE NOT NULL,
  SOURCE_NAME VARCHAR(64) NOT NULL,
  ORDER_COUNT NUMBER,
  GROSS_SALES NUMBER(38,4),
  CURRENCY_CODE VARCHAR(16),
  CAPTURED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
