/* Shopify Bulk API + CoCo — production schedule
   Pair-programmed by SE Community + Cortex Code
   Expires: 2026-12-03

   Safety: CREATE TASK leaves the task suspended. CoCo resumes it only after
   the pilot-store qualification gate passes. */

USE ROLE SHOPIFY_PIPELINE_RL;
USE WAREHOUSE SHOPIFY_PIPELINE_WH;

CREATE TASK IF NOT EXISTS SHOPIFY_NATIVE.CONTROL.DAILY_SHOPIFY_PULL
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  SCHEDULE = 'USING CRON 0 2 * * * UTC'
  SUSPEND_TASK_AFTER_NUM_FAILURES = 3
  USER_TASK_TIMEOUT_MS = 7200000
  COMMENT = 'Daily deterministic Shopify Bulk API pull; resume only after qualification'
AS
  CALL SHOPIFY_NATIVE.CONTROL.PULL_ALL_STORES();

-- Promotion gate — run through CoCo after inspecting QUALIFICATION_RESULTS:
-- UPDATE SHOPIFY_NATIVE.CONTROL.STORE_REGISTRY SET IS_ACTIVE = TRUE
-- WHERE STORE_KEY = 'STORE_ALPHA' AND QUALIFICATION_STATUS = 'PASSED';
-- ALTER TASK SHOPIFY_NATIVE.CONTROL.DAILY_SHOPIFY_PULL RESUME;

SHOW TASKS LIKE 'DAILY_SHOPIFY_PULL' IN SCHEMA SHOPIFY_NATIVE.CONTROL;
