/* Shopify Bulk API + CoCo — typed analytics layer
   Pair-programmed by SE Community + Cortex Code
   Expires: 2026-12-03 */

USE ROLE SHOPIFY_PIPELINE_RL;
USE WAREHOUSE SHOPIFY_PIPELINE_WH;

CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.ORDERS (
  STORE_KEY VARCHAR,
  ORDER_ID VARCHAR,
  ORDER_NAME VARCHAR,
  CREATED_AT TIMESTAMP_TZ,
  UPDATED_AT TIMESTAMP_TZ,
  PROCESSED_AT TIMESTAMP_TZ,
  CANCELLED_AT TIMESTAMP_TZ,
  FINANCIAL_STATUS VARCHAR,
  FULFILLMENT_STATUS VARCHAR,
  CURRENCY_CODE VARCHAR,
  IS_TEST BOOLEAN,
  TOTAL_PRICE NUMBER(38,4),
  TOTAL_DISCOUNTS NUMBER(38,4),
  TOTAL_REFUNDED NUMBER(38,4),
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_TZ
)
  TARGET_LAG = '24 hours'
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
SELECT
  STORE_KEY,
  RECORD:id::VARCHAR AS ORDER_ID,
  RECORD:name::VARCHAR AS ORDER_NAME,
  TRY_TO_TIMESTAMP_TZ(RECORD:createdAt::VARCHAR) AS CREATED_AT,
  TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) AS UPDATED_AT,
  TRY_TO_TIMESTAMP_TZ(RECORD:processedAt::VARCHAR) AS PROCESSED_AT,
  TRY_TO_TIMESTAMP_TZ(RECORD:cancelledAt::VARCHAR) AS CANCELLED_AT,
  RECORD:displayFinancialStatus::VARCHAR AS FINANCIAL_STATUS,
  RECORD:displayFulfillmentStatus::VARCHAR AS FULFILLMENT_STATUS,
  RECORD:currencyCode::VARCHAR AS CURRENCY_CODE,
  COALESCE(RECORD:test::BOOLEAN, FALSE) AS IS_TEST,
  TRY_TO_DECIMAL(RECORD:totalPriceSet:shopMoney:amount::VARCHAR, 38, 4) AS TOTAL_PRICE,
  TRY_TO_DECIMAL(RECORD:totalDiscountsSet:shopMoney:amount::VARCHAR, 38, 4) AS TOTAL_DISCOUNTS,
  TRY_TO_DECIMAL(RECORD:totalRefundedSet:shopMoney:amount::VARCHAR, 38, 4) AS TOTAL_REFUNDED,
  SOURCE_FILE,
  LOADED_AT
FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW
WHERE OBJECT_NAME = 'ORDERS'
  AND RECORD:id::VARCHAR LIKE 'gid://shopify/Order/%'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY STORE_KEY, RECORD:id::VARCHAR
  ORDER BY TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) DESC NULLS LAST, LOADED_AT DESC
) = 1;

CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.ORDER_LINE_ITEMS (
  STORE_KEY VARCHAR,
  LINE_ITEM_ID VARCHAR,
  ORDER_ID VARCHAR,
  TITLE VARCHAR,
  SKU VARCHAR,
  VENDOR VARCHAR,
  QUANTITY NUMBER,
  CURRENT_QUANTITY NUMBER,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_TZ
)
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
WITH LATEST_ORDER_FILES AS (
  SELECT STORE_KEY, RECORD:id::VARCHAR AS ORDER_ID, SOURCE_FILE
  FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW
  WHERE OBJECT_NAME = 'ORDERS'
    AND RECORD:id::VARCHAR LIKE 'gid://shopify/Order/%'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_KEY, RECORD:id::VARCHAR
    ORDER BY TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) DESC NULLS LAST, LOADED_AT DESC
  ) = 1
)
SELECT
  R.STORE_KEY,
  R.RECORD:id::VARCHAR AS LINE_ITEM_ID,
  R.RECORD:__parentId::VARCHAR AS ORDER_ID,
  R.RECORD:title::VARCHAR AS TITLE,
  R.RECORD:sku::VARCHAR AS SKU,
  R.RECORD:vendor::VARCHAR AS VENDOR,
  TRY_TO_NUMBER(R.RECORD:quantity::VARCHAR) AS QUANTITY,
  TRY_TO_NUMBER(R.RECORD:currentQuantity::VARCHAR) AS CURRENT_QUANTITY,
  R.SOURCE_FILE,
  R.LOADED_AT
FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW R
JOIN LATEST_ORDER_FILES L
  ON L.STORE_KEY = R.STORE_KEY
 AND L.ORDER_ID = R.RECORD:__parentId::VARCHAR
 AND L.SOURCE_FILE = R.SOURCE_FILE
WHERE R.OBJECT_NAME = 'ORDERS'
  AND R.RECORD:id::VARCHAR LIKE 'gid://shopify/LineItem/%'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY R.STORE_KEY, R.RECORD:id::VARCHAR
  ORDER BY R.LOADED_AT DESC
) = 1;

CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.ORDER_FULFILLMENTS (
  STORE_KEY VARCHAR,
  FULFILLMENT_ID VARCHAR,
  ORDER_ID VARCHAR,
  STATUS VARCHAR,
  CREATED_AT TIMESTAMP_TZ,
  UPDATED_AT TIMESTAMP_TZ,
  DELIVERED_AT TIMESTAMP_TZ,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_TZ
)
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
WITH LATEST_ORDER_FILES AS (
  SELECT STORE_KEY, RECORD:id::VARCHAR AS ORDER_ID, SOURCE_FILE
  FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW
  WHERE OBJECT_NAME = 'ORDERS'
    AND RECORD:id::VARCHAR LIKE 'gid://shopify/Order/%'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_KEY, RECORD:id::VARCHAR
    ORDER BY TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) DESC NULLS LAST, LOADED_AT DESC
  ) = 1
)
SELECT
  R.STORE_KEY,
  R.RECORD:id::VARCHAR AS FULFILLMENT_ID,
  R.RECORD:__parentId::VARCHAR AS ORDER_ID,
  R.RECORD:status::VARCHAR AS STATUS,
  TRY_TO_TIMESTAMP_TZ(R.RECORD:createdAt::VARCHAR) AS CREATED_AT,
  TRY_TO_TIMESTAMP_TZ(R.RECORD:updatedAt::VARCHAR) AS UPDATED_AT,
  TRY_TO_TIMESTAMP_TZ(R.RECORD:deliveredAt::VARCHAR) AS DELIVERED_AT,
  R.SOURCE_FILE,
  R.LOADED_AT
FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW R
JOIN LATEST_ORDER_FILES L
  ON L.STORE_KEY = R.STORE_KEY
 AND L.ORDER_ID = R.RECORD:__parentId::VARCHAR
 AND L.SOURCE_FILE = R.SOURCE_FILE
WHERE R.OBJECT_NAME = 'ORDERS'
  AND R.RECORD:id::VARCHAR LIKE 'gid://shopify/Fulfillment/%'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY R.STORE_KEY, R.RECORD:id::VARCHAR
  ORDER BY TRY_TO_TIMESTAMP_TZ(R.RECORD:updatedAt::VARCHAR) DESC NULLS LAST, R.LOADED_AT DESC
) = 1;

CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.DAILY_SHOP_ACTIVITY (
  STORE_KEY VARCHAR,
  ACTIVITY_DATE DATE,
  CURRENCY_CODE VARCHAR,
  ORDERS_PLACED NUMBER,
  ORDERS_CANCELLED NUMBER,
  UNITS_SOLD NUMBER,
  GROSS_SALES NUMBER(38,4),
  DISCOUNTS NUMBER(38,4),
  REFUNDS NUMBER(38,4),
  NET_SALES NUMBER(38,4),
  SHIPMENTS_CREATED NUMBER,
  SHIPMENTS_DELIVERED NUMBER
)
  TARGET_LAG = '24 hours'
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
WITH ORDER_DAILY AS (
  SELECT
    STORE_KEY,
    TO_DATE(CONVERT_TIMEZONE('UTC', PROCESSED_AT)) AS ACTIVITY_DATE,
    CURRENCY_CODE,
    COUNT(*) AS ORDERS_PLACED,
    COUNT_IF(CANCELLED_AT IS NOT NULL) AS ORDERS_CANCELLED,
    SUM(TOTAL_PRICE) AS GROSS_SALES,
    SUM(TOTAL_DISCOUNTS) AS DISCOUNTS,
    SUM(TOTAL_REFUNDED) AS REFUNDS,
    SUM(TOTAL_PRICE) - SUM(TOTAL_REFUNDED) AS NET_SALES
  FROM SHOPIFY_NATIVE.ANALYTICS.ORDERS
  WHERE NOT IS_TEST AND PROCESSED_AT IS NOT NULL
  GROUP BY STORE_KEY, ACTIVITY_DATE, CURRENCY_CODE
),
UNIT_DAILY AS (
  SELECT O.STORE_KEY, TO_DATE(CONVERT_TIMEZONE('UTC', O.PROCESSED_AT)) AS ACTIVITY_DATE,
         O.CURRENCY_CODE,
         SUM(L.QUANTITY) AS UNITS_SOLD
  FROM SHOPIFY_NATIVE.ANALYTICS.ORDERS O
  JOIN SHOPIFY_NATIVE.ANALYTICS.ORDER_LINE_ITEMS L
    ON L.STORE_KEY = O.STORE_KEY AND L.ORDER_ID = O.ORDER_ID
  WHERE NOT O.IS_TEST
  GROUP BY O.STORE_KEY, ACTIVITY_DATE, O.CURRENCY_CODE
),
SHIPMENT_DAILY AS (
  SELECT F.STORE_KEY, TO_DATE(CONVERT_TIMEZONE('UTC', F.CREATED_AT)) AS ACTIVITY_DATE,
         O.CURRENCY_CODE,
         COUNT(*) AS SHIPMENTS_CREATED,
         COUNT_IF(F.DELIVERED_AT IS NOT NULL) AS SHIPMENTS_DELIVERED
  FROM SHOPIFY_NATIVE.ANALYTICS.ORDER_FULFILLMENTS F
  JOIN SHOPIFY_NATIVE.ANALYTICS.ORDERS O
    ON O.STORE_KEY = F.STORE_KEY AND O.ORDER_ID = F.ORDER_ID
  GROUP BY F.STORE_KEY, ACTIVITY_DATE, O.CURRENCY_CODE
)
SELECT
  O.STORE_KEY,
  O.ACTIVITY_DATE,
  O.CURRENCY_CODE,
  O.ORDERS_PLACED,
  O.ORDERS_CANCELLED,
  COALESCE(U.UNITS_SOLD, 0) AS UNITS_SOLD,
  O.GROSS_SALES,
  O.DISCOUNTS,
  O.REFUNDS,
  O.NET_SALES,
  COALESCE(S.SHIPMENTS_CREATED, 0) AS SHIPMENTS_CREATED,
  COALESCE(S.SHIPMENTS_DELIVERED, 0) AS SHIPMENTS_DELIVERED
FROM ORDER_DAILY O
LEFT JOIN UNIT_DAILY U
  ON U.STORE_KEY = O.STORE_KEY AND U.ACTIVITY_DATE = O.ACTIVITY_DATE
 AND U.CURRENCY_CODE = O.CURRENCY_CODE
LEFT JOIN SHIPMENT_DAILY S
  ON S.STORE_KEY = O.STORE_KEY AND S.ACTIVITY_DATE = O.ACTIVITY_DATE
 AND S.CURRENCY_CODE = O.CURRENCY_CODE;
