/* Shopify Bulk API + CoCo — evidence used by Desktop and automations
   Pair-programmed by SE Community + Cortex Code
   Expires: 2026-12-03 */

CREATE OR REPLACE VIEW SHOPIFY_NATIVE.CONTROL.V_PIPELINE_HEALTH AS
WITH LAST_RUN AS (
  SELECT STORE_KEY, OBJECT_NAME, STATUS, COMPLETED_AT, ROWS_LOADED,
         ERROR_CLASS, ERROR_MESSAGE
  FROM SHOPIFY_NATIVE.CONTROL.PULL_RUN_LOG
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_KEY, OBJECT_NAME ORDER BY STARTED_AT DESC
  ) = 1
)
SELECT
  R.STORE_KEY,
  R.SHOP_DOMAIN,
  R.IS_ACTIVE,
  R.QUALIFICATION_STATUS,
  L.OBJECT_NAME,
  L.STATUS AS LAST_RUN_STATUS,
  L.COMPLETED_AT AS LAST_COMPLETED_AT,
  DATEDIFF('hour', L.COMPLETED_AT, CURRENT_TIMESTAMP()) AS HOURS_SINCE_COMPLETION,
  L.ROWS_LOADED,
  L.ERROR_CLASS,
  L.ERROR_MESSAGE
FROM SHOPIFY_NATIVE.CONTROL.STORE_REGISTRY R
LEFT JOIN LAST_RUN L ON L.STORE_KEY = R.STORE_KEY;

-- Zero-lag task history (last 7 days). Push filters into the table function.
SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, QUERY_ID, ERROR_CODE, ERROR_MESSAGE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
  TASK_NAME => 'DAILY_SHOPIFY_PULL',
  SCHEDULED_TIME_RANGE_START => DATEADD('day', -7, CURRENT_TIMESTAMP()),
  SCHEDULED_TIME_RANGE_END => CURRENT_TIMESTAMP(),
  RESULT_LIMIT => 10000
))
WHERE DATABASE_NAME = 'SHOPIFY_NATIVE' AND SCHEMA_NAME = 'CONTROL'
ORDER BY SCHEDULED_TIME DESC;

USE DATABASE SHOPIFY_NATIVE;
SELECT NAME, STATE, STATE_MESSAGE, REFRESH_ACTION, REFRESH_START_TIME, REFRESH_END_TIME
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
  NAME_PREFIX => 'SHOPIFY_NATIVE.ANALYTICS',
  ERROR_ONLY => TRUE,
  DATA_TIMESTAMP_START => DATEADD('day', -30, CURRENT_TIMESTAMP())
))
ORDER BY REFRESH_START_TIME DESC;

-- Per-store warehouse cost attribution via the query tag set by PULL_ALL_STORES.
SELECT
  REGEXP_SUBSTR(QUERY_TAG, 'SHOPIFY_NATIVE:([^:]+)', 1, 1, 'e', 1) AS STORE_KEY,
  DATE_TRUNC('week', START_TIME) AS USAGE_WEEK,
  SUM(CREDITS_ATTRIBUTED_COMPUTE) AS CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY
WHERE START_TIME >= DATEADD('day', -90, CURRENT_TIMESTAMP())
  AND QUERY_TAG LIKE 'SHOPIFY_NATIVE:%'
GROUP BY STORE_KEY, USAGE_WEEK
ORDER BY USAGE_WEEK DESC, CREDITS DESC;

-- Qualification evidence. CoCo reads this before activating a store or task.
SELECT STORE_KEY, GATE_NAME, PASSED, EVIDENCE, CHECKED_AT
FROM SHOPIFY_NATIVE.CONTROL.QUALIFICATION_RESULTS
ORDER BY STORE_KEY, CHECKED_AT, GATE_NAME;

-- Stage inventory for retention review.
ALTER STAGE SHOPIFY_NATIVE.LANDING.SHOPIFY_STAGE REFRESH;
SELECT RELATIVE_PATH, SIZE, LAST_MODIFIED
FROM DIRECTORY(@SHOPIFY_NATIVE.LANDING.SHOPIFY_STAGE)
ORDER BY LAST_MODIFIED DESC;
