/* Shopify Bulk API + CoCo — teardown
   Pair-programmed by SE Community + Cortex Code
   Expires: 2026-12-03 */

USE ROLE SHOPIFY_PIPELINE_RL;
ALTER TASK IF EXISTS SHOPIFY_NATIVE.CONTROL.DAILY_SHOPIFY_PULL SUSPEND;
DROP TASK IF EXISTS SHOPIFY_NATIVE.CONTROL.DAILY_SHOPIFY_PULL;

USE ROLE ACCOUNTADMIN;
DROP INTEGRATION IF EXISTS SHOPIFY_NATIVE_EAI;
-- Drop store secrets explicitly after confirming they are not shared.
-- DROP SECRET IF EXISTS SHOPIFY_NATIVE.CONTROL.SHOPIFY_STORE_ALPHA_CREDENTIALS;
DROP DATABASE IF EXISTS SHOPIFY_NATIVE;
DROP WAREHOUSE IF EXISTS SHOPIFY_PIPELINE_WH;
DROP ROLE IF EXISTS SHOPIFY_PIPELINE_RL;
