USE DATABASE SNOWFLAKE_EXAMPLE;
USE SCHEMA IOT_LIFECYCLE;
USE WAREHOUSE SFE_IOT_LIFECYCLE_WH;

CREATE OR REPLACE VIEW V_FLEET_STATUS
  COMMENT = 'DEMO: Latest position and status per vehicle (Expires: 2026-06-11)'
AS
SELECT
    fv.VEHICLE_ID,
    fv.LICENSE_PLATE,
    fv.DRIVER_NAME,
    fv.VEHICLE_TYPE,
    fv.HOME_DEPOT,
    fv.STATUS          AS VEHICLE_STATUS,
    gps.LATITUDE       AS CURRENT_LAT,
    gps.LONGITUDE      AS CURRENT_LNG,
    gps.SPEED_MPH      AS CURRENT_SPEED,
    gps.HEADING        AS CURRENT_HEADING,
    gps.ENGINE_STATUS,
    gps.TIMESTAMP      AS LAST_PING,
    r.ROUTE_NAME       AS ASSIGNED_ROUTE,
    CASE
        WHEN gps.ENGINE_STATUS = 'IDLE' AND gps.SPEED_MPH = 0 THEN 'AT_STOP'
        WHEN gps.SPEED_MPH > 0 THEN 'IN_TRANSIT'
        ELSE 'PARKED'
    END AS MOVEMENT_STATUS
FROM FLEET_VEHICLES fv
LEFT JOIN GPS_TELEMETRY gps
    ON fv.VEHICLE_ID = gps.VEHICLE_ID
    AND gps.TIMESTAMP = (
        SELECT MAX(g2.TIMESTAMP)
        FROM GPS_TELEMETRY g2
        WHERE g2.VEHICLE_ID = fv.VEHICLE_ID
    )
LEFT JOIN ROUTES r ON fv.VEHICLE_ID = r.VEHICLE_ID;

CREATE OR REPLACE VIEW V_GARMENT_LIFECYCLE
  COMMENT = 'DEMO: Latest lifecycle stage per garment with age metrics (Expires: 2026-06-11)'
AS
SELECT
    g.GARMENT_ID,
    g.RFID_TAG,
    g.GARMENT_TYPE,
    g.SIZE,
    g.COLOR,
    g.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    g.STATUS           AS GARMENT_STATUS,
    g.WASH_COUNT,
    g.USEFUL_LIFE_CYCLES,
    g.REPLACEMENT_COST,
    g.DAYS_AT_LOCATION,
    g.LIFECYCLE_STATE,
    ROUND(g.WASH_COUNT * 100.0 / NULLIF(g.USEFUL_LIFE_CYCLES, 0), 1) AS WASH_CYCLE_PCT_OF_LIFE,
    g.ASSIGNED_DATE,
    DATEDIFF('day', g.ASSIGNED_DATE, CURRENT_DATE()) AS DAYS_IN_SERVICE,
    le.EVENT_TYPE      AS LAST_EVENT,
    le.EVENT_TIMESTAMP AS LAST_EVENT_TIME,
    le.LOCATION        AS LAST_EVENT_LOCATION,
    DATEDIFF('hour', le.EVENT_TIMESTAMP, CURRENT_TIMESTAMP()) AS HOURS_SINCE_LAST_EVENT
FROM GARMENTS g
LEFT JOIN CUSTOMERS c ON g.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN GARMENT_EVENTS le
    ON g.GARMENT_ID = le.GARMENT_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY g.GARMENT_ID ORDER BY le.EVENT_TIMESTAMP DESC NULLS LAST) = 1;

CREATE OR REPLACE VIEW V_GARMENT_LOSS_RATE
  COMMENT = 'DEMO: Garment loss rate by customer and type (Expires: 2026-06-11)'
AS
SELECT
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    g.GARMENT_TYPE,
    COUNT(*)                                      AS TOTAL_GARMENTS,
    COUNT_IF(g.STATUS = 'LOST')                   AS LOST_COUNT,
    ROUND(COUNT_IF(g.STATUS = 'LOST') * 100.0 / NULLIF(COUNT(*), 0), 2) AS LOSS_RATE_PCT
FROM GARMENTS g
JOIN CUSTOMERS c ON g.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME, c.INDUSTRY, g.GARMENT_TYPE;

CREATE OR REPLACE VIEW V_ROUTE_EFFICIENCY
  COMMENT = 'DEMO: Route performance with fuel variance analysis (Expires: 2026-06-11)'
AS
SELECT
    r.ROUTE_ID,
    r.ROUTE_NAME,
    r.DAY_OF_WEEK,
    fv.DRIVER_NAME,
    r.STOP_COUNT,
    r.ESTIMATED_MILES,
    r.FUEL_COST_USD,
    r.AVG_FUEL_COST_USD,
    ROUND((r.FUEL_COST_USD - r.AVG_FUEL_COST_USD) * 100.0 / NULLIF(r.AVG_FUEL_COST_USD, 0), 1) AS FUEL_VARIANCE_PCT,
    CASE
        WHEN (r.FUEL_COST_USD - r.AVG_FUEL_COST_USD) * 100.0 / NULLIF(r.AVG_FUEL_COST_USD, 0) > 10 THEN 'HIGH'
        WHEN (r.FUEL_COST_USD - r.AVG_FUEL_COST_USD) * 100.0 / NULLIF(r.AVG_FUEL_COST_USD, 0) > 5  THEN 'MODERATE'
        ELSE 'NORMAL'
    END AS EFFICIENCY_BAND,
    COUNT(DISTINCT gps.TELEMETRY_ID)                           AS GPS_PINGS,
    MIN(gps.TIMESTAMP)                                         AS ROUTE_START,
    MAX(gps.TIMESTAMP)                                         AS ROUTE_END,
    DATEDIFF('minute', MIN(gps.TIMESTAMP), MAX(gps.TIMESTAMP)) AS ROUTE_DURATION_MIN,
    ROUND(AVG(gps.SPEED_MPH), 1)                               AS AVG_SPEED_MPH,
    MAX(gps.SPEED_MPH)                                         AS MAX_SPEED_MPH
FROM ROUTES r
JOIN FLEET_VEHICLES fv ON r.VEHICLE_ID = fv.VEHICLE_ID
LEFT JOIN GPS_TELEMETRY gps ON r.VEHICLE_ID = gps.VEHICLE_ID
GROUP BY r.ROUTE_ID, r.ROUTE_NAME, r.DAY_OF_WEEK, fv.DRIVER_NAME, r.STOP_COUNT, r.ESTIMATED_MILES, r.FUEL_COST_USD, r.AVG_FUEL_COST_USD;

CREATE OR REPLACE VIEW V_FINANCIAL_SUMMARY
  COMMENT = 'DEMO: Monthly P&L with budget variance (Expires: 2026-06-11)'
AS
SELECT
    fa.FISCAL_YEAR,
    fa.FISCAL_QUARTER,
    fa.FISCAL_MONTH,
    gl.GL_CATEGORY,
    gl.GL_TYPE,
    SUM(fa.AMOUNT)                                                    AS ACTUAL_AMOUNT,
    SUM(fb.BUDGET_AMOUNT)                                             AS BUDGET_AMOUNT,
    SUM(fa.AMOUNT) - SUM(fb.BUDGET_AMOUNT)                            AS VARIANCE,
    ROUND((SUM(fa.AMOUNT) - SUM(fb.BUDGET_AMOUNT)) * 100.0
          / NULLIF(SUM(fb.BUDGET_AMOUNT), 0), 2)                      AS VARIANCE_PCT
FROM FINANCIAL_ACTUALS fa
JOIN GL_CODES gl ON fa.GL_CODE = gl.GL_CODE
LEFT JOIN FINANCIAL_BUDGET fb
    ON fa.FISCAL_MONTH = fb.FISCAL_MONTH AND fa.GL_CODE = fb.GL_CODE
GROUP BY fa.FISCAL_YEAR, fa.FISCAL_QUARTER, fa.FISCAL_MONTH, gl.GL_CATEGORY, gl.GL_TYPE;

CREATE OR REPLACE VIEW V_REVENUE_BY_CUSTOMER
  COMMENT = 'DEMO: Revenue per customer from invoices (Expires: 2026-06-11)'
AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    c.CITY,
    c.CSAT_SCORE,
    c.RETURN_RATE_PCT,
    c.INVOICE_DISPUTE_COUNT,
    COUNT(DISTINCT i.INVOICE_ID)       AS INVOICE_COUNT,
    SUM(i.TOTAL_AMOUNT)                AS TOTAL_REVENUE,
    AVG(i.TOTAL_AMOUNT)                AS AVG_INVOICE,
    COUNT_IF(i.PAYMENT_STATUS = 'OVERDUE') AS OVERDUE_COUNT,
    SUM(CASE WHEN i.PAYMENT_STATUS = 'PENDING' THEN i.TOTAL_AMOUNT ELSE 0 END) AS OUTSTANDING_AR
FROM CUSTOMERS c
LEFT JOIN INVOICES i ON c.CUSTOMER_ID = i.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.INDUSTRY, c.CITY, c.CSAT_SCORE, c.RETURN_RATE_PCT, c.INVOICE_DISPUTE_COUNT;

CREATE OR REPLACE VIEW V_ZOMBIE_GARMENTS
  COMMENT = 'DEMO: Garments stalled at customer sites >14 days -- zombie detection (Expires: 2026-06-11)'
AS
SELECT
    g.GARMENT_ID,
    g.RFID_TAG,
    g.GARMENT_TYPE,
    g.SIZE,
    g.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    c.ROUTE_ID,
    g.DAYS_AT_LOCATION,
    g.WASH_COUNT,
    g.USEFUL_LIFE_CYCLES,
    g.REPLACEMENT_COST,
    ROUND(g.WASH_COUNT * 100.0 / NULLIF(g.USEFUL_LIFE_CYCLES, 0), 1) AS WASH_CYCLE_PCT_OF_LIFE,
    g.LIFECYCLE_STATE
FROM GARMENTS g
JOIN CUSTOMERS c ON g.CUSTOMER_ID = c.CUSTOMER_ID
WHERE g.LIFECYCLE_STATE = 'ZOMBIE'
  AND g.DAYS_AT_LOCATION > 14;

CREATE OR REPLACE VIEW V_CUSTOMER_RISK
  COMMENT = 'DEMO: Per-customer risk rollup with financial exposure (Expires: 2026-06-11)'
AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    c.CITY,
    c.LATITUDE,
    c.LONGITUDE,
    c.MONTHLY_VALUE,
    c.CSAT_SCORE,
    c.INVOICE_DISPUTE_COUNT,
    c.RETURN_RATE_PCT,
    COUNT_IF(g.LIFECYCLE_STATE = 'ZOMBIE')          AS ZOMBIE_COUNT,
    SUM(CASE WHEN g.LIFECYCLE_STATE = 'ZOMBIE' THEN g.REPLACEMENT_COST ELSE 0 END) AS FINANCIAL_EXPOSURE_USD,
    COUNT_IF(g.WASH_COUNT >= g.USEFUL_LIFE_CYCLES * 0.9) AS NEAR_RETIREMENT_COUNT,
    CASE
        WHEN COUNT_IF(g.LIFECYCLE_STATE = 'ZOMBIE') >= 50 OR c.CSAT_SCORE < 3.5 THEN 'RED'
        WHEN COUNT_IF(g.LIFECYCLE_STATE = 'ZOMBIE') >= 10 OR c.CSAT_SCORE < 4.0 THEN 'YELLOW'
        WHEN c.RETURN_RATE_PCT >= 99.0 THEN 'GREEN'
        ELSE 'NORMAL'
    END AS RISK_BAND
FROM CUSTOMERS c
LEFT JOIN GARMENTS g ON c.CUSTOMER_ID = g.CUSTOMER_ID AND g.STATUS = 'IN_SERVICE'
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.INDUSTRY, c.CITY, c.LATITUDE, c.LONGITUDE,
         c.MONTHLY_VALUE, c.CSAT_SCORE, c.INVOICE_DISPUTE_COUNT, c.RETURN_RATE_PCT;

CREATE OR REPLACE VIEW V_RETIREMENT_RISK
  COMMENT = 'DEMO: Garments approaching end-of-life (>90% wash cycles used) (Expires: 2026-06-11)'
AS
SELECT
    g.GARMENT_ID,
    g.RFID_TAG,
    g.GARMENT_TYPE,
    g.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    g.WASH_COUNT,
    g.USEFUL_LIFE_CYCLES,
    ROUND(g.WASH_COUNT * 100.0 / NULLIF(g.USEFUL_LIFE_CYCLES, 0), 1) AS WASH_CYCLE_PCT_OF_LIFE,
    g.USEFUL_LIFE_CYCLES - g.WASH_COUNT AS REMAINING_CYCLES,
    g.REPLACEMENT_COST,
    g.LIFECYCLE_STATE,
    g.DAYS_AT_LOCATION
FROM GARMENTS g
JOIN CUSTOMERS c ON g.CUSTOMER_ID = c.CUSTOMER_ID
WHERE g.WASH_COUNT >= g.USEFUL_LIFE_CYCLES * 0.9
  AND g.STATUS = 'IN_SERVICE';

CREATE OR REPLACE VIEW V_RETENTION_ALERTS
  COMMENT = 'DEMO: Active retention alerts with driver talking points (Expires: 2026-06-11)'
AS
SELECT
    ra.ALERT_ID,
    ra.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.INDUSTRY,
    c.ROUTE_ID,
    r.ROUTE_NAME,
    fv.DRIVER_NAME,
    ra.ALERT_DATE,
    ra.MISSING_TAG_COUNT,
    ra.FINANCIAL_SAVE_USD,
    ra.DRIVER_TALKING_POINT,
    ra.STATUS AS ALERT_STATUS,
    c.CSAT_SCORE,
    c.RETURN_RATE_PCT
FROM RETENTION_ALERTS ra
JOIN CUSTOMERS c ON ra.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN ROUTES r ON c.ROUTE_ID = r.ROUTE_ID
LEFT JOIN FLEET_VEHICLES fv ON r.VEHICLE_ID = fv.VEHICLE_ID;
