USE DATABASE SNOWFLAKE_EXAMPLE;
USE SCHEMA IOT_LIFECYCLE;
USE WAREHOUSE SFE_IOT_LIFECYCLE_WH;

CREATE OR REPLACE STREAM GPS_TELEMETRY_STREAM
  ON TABLE GPS_TELEMETRY
  APPEND_ONLY = TRUE
  COMMENT = 'DEMO: Captures new GPS pings for fleet status updates (Expires: 2026-06-11)';

CREATE OR REPLACE TASK REFRESH_FLEET_STATUS
  WAREHOUSE = SFE_IOT_LIFECYCLE_WH
  SCHEDULE  = '5 MINUTE'
  COMMENT   = 'DEMO: Refreshes fleet status aggregate from GPS stream (Expires: 2026-06-11)'
  WHEN SYSTEM$STREAM_HAS_DATA('GPS_TELEMETRY_STREAM')
AS
  SELECT COUNT(*) FROM GPS_TELEMETRY_STREAM;
