/*
  guide-shopify-multistore-snowflake — sql/openflow/06_analytics_layer.sql
  Pair-programmed by SE Community + Cortex Code
  Expires: 2026-12-21

  PURPOSE
    Turn N per-store schemas into one queryable model that satisfies the shared
    analytics contract:
      SHOPIFY_ANALYTICS.CORE.ORDERS_ALL             (UNION ALL of every store)
      SHOPIFY_ANALYTICS.CORE.ORDER_LINE_ITEMS_ALL
      SHOPIFY_ANALYTICS.CORE.ORDER_FULFILLMENTS_ALL
      SHOPIFY_ANALYTICS.CORE.FULFILLMENT_ORDERS_ALL
      SHOPIFY_ANALYTICS.CORE.DAILY_SHOP_ACTIVITY    (the contract)
      SHOPIFY_CONTROL.META.V_DAILY_SHOP_ACTIVITY    (published contract surface)
      SHOPIFY_CONTROL.META.V_STORE_FRESHNESS        (published ops surface)

    The *_ALL Dynamic Tables are GENERATED by REBUILD_ANALYTICS_DTS() from the
    shared registry, because the connector writes one schema per store and the
    set of schemas changes as stores are added. Re-run it every time a store is
    activated or deactivated.

    DAILY_SHOP_ACTIVITY is hand-written, not generated: it reads the *_ALL
    tables, which already carry every store.

  CONTRACT
    The column list, grain, and every measure definition are specified once in
    README.md ("The one analytics contract") and encoded in
    SHOPIFY_CONTROL.META.CONTRACT_COLUMNS. The native path produces the same
    14 columns from different SQL. After deploying, verify with:
      SELECT COUNT_IF(STATUS <> 'OK') FROM SHOPIFY_CONTROL.META.V_CONTRACT_CONFORMANCE;

  RAW COLUMN CONTRACT
    Columns referenced here are the promoted columns defined in
    config/shopify_object_override.json plus the connector's own columns:
      ID, SHOP_URL (merge key), __PARENT_ID (child tables),
      __SNOWFLAKE_IS_DELETED, __SNOWFLAKE_DELETED_AT.
    The raw JSON payload column name is NOT documented. After the first store
    loads, run  DESCRIBE TABLE SHOPIFY_RAW.<STORE>.ORDERS  and, if any column
    below is missing, adjust the override or this file before rebuilding.

  RUN AS      OPENFLOW_ADMIN
  RUNTIME     < 1 minute to create; first DT refresh depends on data volume
  SOURCE      https://docs.snowflake.com/en/user-guide/dynamic-tables/overview
*/

USE ROLE OPENFLOW_ADMIN;

CREATE DATABASE IF NOT EXISTS SHOPIFY_ANALYTICS
  COMMENT = 'Cross-store Shopify analytics layer (Dynamic Tables), Openflow path';

CREATE SCHEMA IF NOT EXISTS SHOPIFY_ANALYTICS.CORE
  COMMENT = 'Consolidated orders, line items, fulfillments, daily activity';

-- Dedicated warehouse for DT refreshes so ingestion cost stays separable
CREATE WAREHOUSE IF NOT EXISTS SHOPIFY_ANALYTICS_WH
  WAREHOUSE_SIZE               = 'XSMALL'
  AUTO_SUSPEND                 = 60
  AUTO_RESUME                  = TRUE
  INITIALLY_SUSPENDED          = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 3600
  COMMENT = 'Dynamic Table refreshes for SHOPIFY_ANALYTICS';

-- 1. Generator: rebuild the UNION ALL Dynamic Tables from the registry ---------
--    Reads the SHARED registry. Only IS_ACTIVE stores are included, so
--    activating a store is what puts it on the contract surface.
CREATE OR REPLACE PROCEDURE SHOPIFY_ANALYTICS.CORE.REBUILD_ANALYTICS_DTS(
  P_TARGET_LAG VARCHAR DEFAULT '24 hours'
)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Regenerates SHOPIFY_ANALYTICS.CORE.*_ALL Dynamic Tables as UNION ALL over every active store schema.'
EXECUTE AS CALLER
AS
$$
DECLARE
  V_STORES  RESULTSET;
  V_ORDERS  VARCHAR DEFAULT '';
  V_ITEMS   VARCHAR DEFAULT '';
  V_FULFIL  VARCHAR DEFAULT '';
  V_FO      VARCHAR DEFAULT '';
  V_SEP     VARCHAR DEFAULT '';
  V_N       INTEGER DEFAULT 0;
BEGIN
  V_STORES := (SELECT STORE_KEY FROM SHOPIFY_CONTROL.META.STORE_REGISTRY
               WHERE IS_ACTIVE ORDER BY STORE_KEY);

  FOR REC IN V_STORES DO
    V_N := V_N + 1;

    V_ORDERS := :V_ORDERS || :V_SEP ||
      'SELECT ''' || REC.STORE_KEY || ''' AS store_key, shop_url, id AS order_id, order_name, ' ||
      'created_at, updated_at, processed_at, cancelled_at, financial_status, fulfillment_status, ' ||
      'currency_code, is_test, customer_id, total_price, subtotal_price, total_tax, total_shipping, ' ||
      'total_discounts, total_refunded, ship_country, ship_province, ' ||
      '__snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || REC.STORE_KEY || '.ORDERS';

    V_ITEMS := :V_ITEMS || :V_SEP ||
      'SELECT ''' || REC.STORE_KEY || ''' AS store_key, shop_url, id AS line_item_id, ' ||
      '__parent_id AS order_gid, title, sku, vendor, quantity, current_quantity, product_id, ' ||
      'variant_id, unit_price, discounted_total, __snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || REC.STORE_KEY || '.ORDER_LINE_ITEMS';

    V_FULFIL := :V_FULFIL || :V_SEP ||
      'SELECT ''' || REC.STORE_KEY || ''' AS store_key, shop_url, id AS fulfillment_id, ' ||
      '__parent_id AS order_gid, status, created_at, updated_at, delivered_at, ' ||
      'estimated_delivery_at, tracking_company, tracking_number, ' ||
      '__snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || REC.STORE_KEY || '.ORDER_FULFILLMENTS';

    V_FO := :V_FO || :V_SEP ||
      'SELECT ''' || REC.STORE_KEY || ''' AS store_key, shop_url, id AS fulfillment_order_id, ' ||
      'order_id, created_at, updated_at, status, request_status, fulfill_by, location_name, ' ||
      'location_id, delivery_method, __snowflake_is_deleted AS is_deleted ' ||
      'FROM SHOPIFY_RAW.' || REC.STORE_KEY || '.FULFILLMENT_ORDERS';

    V_SEP := ' UNION ALL ';
  END FOR;

  IF (:V_N = 0) THEN
    RETURN 'ERROR: no ACTIVE stores in STORE_REGISTRY. '
        || 'Fix: qualify a store, then UPDATE SHOPIFY_CONTROL.META.STORE_REGISTRY SET IS_ACTIVE = TRUE.';
  END IF;

  -- Apostrophes inside a generated COMMENT would terminate the outer string;
  -- these comments deliberately contain none.
  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.ORDERS_ALL ' ||
    'TARGET_LAG = ''' || :P_TARGET_LAG || ''' WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Orders from all active stores; generated by REBUILD_ANALYTICS_DTS'' AS ' || :V_ORDERS;

  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.ORDER_LINE_ITEMS_ALL ' ||
    'TARGET_LAG = DOWNSTREAM WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Order line items from all active stores; generated'' AS ' || :V_ITEMS;

  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.ORDER_FULFILLMENTS_ALL ' ||
    'TARGET_LAG = DOWNSTREAM WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Shipments and fulfillments from all active stores; generated'' AS ' || :V_FULFIL;

  EXECUTE IMMEDIATE 'CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.FULFILLMENT_ORDERS_ALL ' ||
    'TARGET_LAG = DOWNSTREAM WAREHOUSE = SHOPIFY_ANALYTICS_WH REFRESH_MODE = AUTO ' ||
    'COMMENT = ''Fulfillment orders from all active stores; generated'' AS ' || :V_FO;

  RETURN 'OK: rebuilt 4 Dynamic Tables over ' || :V_N || ' active stores with TARGET_LAG '
      || :P_TARGET_LAG || '. DAILY_SHOP_ACTIVITY follows via DOWNSTREAM.';
END;
$$;

CALL SHOPIFY_ANALYTICS.CORE.REBUILD_ANALYTICS_DTS('24 hours');

-- 2. DAILY_SHOP_ACTIVITY: the contract ----------------------------------------
--    Grain: (store_key, activity_date, currency_code). See README.md.
--
--    Join notes, because both are load-bearing:
--
--    * ship_day LEFT JOINs ORDERS_ALL only to obtain the order's currency, so a
--      shipment whose parent order is outside the loaded window still counts,
--      with a NULL currency_code. An inner join would silently drop it.
--
--    * order_day FULL OUTER JOINs ship_day. A LEFT JOIN would drop every day
--      that had shipments but no orders processed -- routine whenever orders
--      placed on Monday ship on Wednesday and Wednesday had no new orders.
--      Those are real days with real shipment counts.
--
--    * currency_code is in the join predicate. Without it, one ship_day row
--      fans out across every currency row for a multi-currency store and
--      shipment counts are multiplied.
--
--    * units_day is grouped by currency for the same reason.
--
--    All measures are COALESCEd to 0: a row exists only when there was order or
--    shipment activity, so "no orders" genuinely means zero, not unknown.
CREATE OR REPLACE DYNAMIC TABLE SHOPIFY_ANALYTICS.CORE.DAILY_SHOP_ACTIVITY
  TARGET_LAG   = DOWNSTREAM
  WAREHOUSE    = SHOPIFY_ANALYTICS_WH
  REFRESH_MODE = AUTO
  COMMENT      = 'Contract surface: one row per store per UTC day per currency. Excludes test and soft-deleted orders.'
AS
WITH ORDERS AS (
  SELECT
    STORE_KEY,
    ORDER_ID,
    CURRENCY_CODE,
    CAST(CONVERT_TIMEZONE('UTC', PROCESSED_AT) AS DATE) AS ACTIVITY_DATE,
    TOTAL_PRICE,
    TOTAL_DISCOUNTS,
    TOTAL_REFUNDED,
    CANCELLED_AT
  FROM SHOPIFY_ANALYTICS.CORE.ORDERS_ALL
  WHERE NOT IS_DELETED
    AND NOT COALESCE(IS_TEST, FALSE)
    AND PROCESSED_AT IS NOT NULL
),
ORDER_DAY AS (
  SELECT
    STORE_KEY,
    ACTIVITY_DATE,
    CURRENCY_CODE,
    COUNT(*)                               AS ORDERS_PLACED,
    COUNT_IF(CANCELLED_AT IS NOT NULL)     AS ORDERS_CANCELLED,
    SUM(TOTAL_PRICE)                       AS GROSS_SALES,
    SUM(TOTAL_DISCOUNTS)                   AS DISCOUNTS,
    SUM(TOTAL_REFUNDED)                    AS REFUNDS,
    SUM(TOTAL_PRICE) - SUM(TOTAL_REFUNDED) AS NET_SALES
  FROM ORDERS
  GROUP BY STORE_KEY, ACTIVITY_DATE, CURRENCY_CODE
),
UNITS_DAY AS (
  SELECT
    O.STORE_KEY,
    O.ACTIVITY_DATE,
    O.CURRENCY_CODE,
    SUM(LI.QUANTITY) AS UNITS_SOLD
  FROM ORDERS O
  JOIN SHOPIFY_ANALYTICS.CORE.ORDER_LINE_ITEMS_ALL LI
    ON LI.STORE_KEY = O.STORE_KEY
   AND LI.ORDER_GID = 'gid://shopify/Order/' || O.ORDER_ID
  WHERE NOT LI.IS_DELETED
  GROUP BY O.STORE_KEY, O.ACTIVITY_DATE, O.CURRENCY_CODE
),
SHIP_DAY AS (
  SELECT
    F.STORE_KEY,
    CAST(CONVERT_TIMEZONE('UTC', F.CREATED_AT) AS DATE) AS ACTIVITY_DATE,
    O.CURRENCY_CODE,
    COUNT(*)                               AS SHIPMENTS_CREATED,
    COUNT_IF(F.STATUS = 'SUCCESS')         AS SHIPMENTS_SUCCESS,
    COUNT_IF(F.DELIVERED_AT IS NOT NULL)   AS SHIPMENTS_DELIVERED
  FROM SHOPIFY_ANALYTICS.CORE.ORDER_FULFILLMENTS_ALL F
  LEFT JOIN SHOPIFY_ANALYTICS.CORE.ORDERS_ALL O
    ON O.STORE_KEY = F.STORE_KEY
   AND 'gid://shopify/Order/' || O.ORDER_ID = F.ORDER_GID
  WHERE NOT F.IS_DELETED
    -- Orphan shipments keep a NULL IS_TEST and survive; test-order shipments do not.
    AND NOT COALESCE(O.IS_TEST, FALSE)
  -- Group by the expression, not the ACTIVITY_DATE alias: an alias here can
  -- resolve to a same-named column on the joined table instead of the output
  -- column, which fails or silently regroups. Verified against Snowflake.
  GROUP BY F.STORE_KEY, CAST(CONVERT_TIMEZONE('UTC', F.CREATED_AT) AS DATE), O.CURRENCY_CODE
),
DAY_FRAME AS (
  SELECT
    COALESCE(OD.STORE_KEY,     SD.STORE_KEY)     AS STORE_KEY,
    COALESCE(OD.ACTIVITY_DATE, SD.ACTIVITY_DATE) AS ACTIVITY_DATE,
    COALESCE(OD.CURRENCY_CODE, SD.CURRENCY_CODE) AS CURRENCY_CODE,
    COALESCE(OD.ORDERS_PLACED,       0)          AS ORDERS_PLACED,
    COALESCE(OD.ORDERS_CANCELLED,    0)          AS ORDERS_CANCELLED,
    COALESCE(OD.GROSS_SALES,         0)          AS GROSS_SALES,
    COALESCE(OD.DISCOUNTS,           0)          AS DISCOUNTS,
    COALESCE(OD.REFUNDS,             0)          AS REFUNDS,
    COALESCE(OD.NET_SALES,           0)          AS NET_SALES,
    COALESCE(SD.SHIPMENTS_CREATED,   0)          AS SHIPMENTS_CREATED,
    COALESCE(SD.SHIPMENTS_SUCCESS,   0)          AS SHIPMENTS_SUCCESS,
    COALESCE(SD.SHIPMENTS_DELIVERED, 0)          AS SHIPMENTS_DELIVERED
  FROM ORDER_DAY OD
  FULL OUTER JOIN SHIP_DAY SD
    ON SD.STORE_KEY     = OD.STORE_KEY
   AND SD.ACTIVITY_DATE = OD.ACTIVITY_DATE
   AND SD.CURRENCY_CODE = OD.CURRENCY_CODE
)
SELECT
  D.STORE_KEY,
  R.SHOP_DOMAIN                     AS SHOP_URL,
  D.ACTIVITY_DATE,
  D.CURRENCY_CODE,
  D.ORDERS_PLACED,
  D.ORDERS_CANCELLED,
  COALESCE(U.UNITS_SOLD, 0)         AS UNITS_SOLD,
  D.GROSS_SALES,
  D.DISCOUNTS,
  D.REFUNDS,
  D.NET_SALES,
  D.SHIPMENTS_CREATED,
  D.SHIPMENTS_SUCCESS,
  D.SHIPMENTS_DELIVERED
FROM DAY_FRAME D
LEFT JOIN UNITS_DAY U
  ON U.STORE_KEY     = D.STORE_KEY
 AND U.ACTIVITY_DATE = D.ACTIVITY_DATE
 AND U.CURRENCY_CODE = D.CURRENCY_CODE
LEFT JOIN SHOPIFY_CONTROL.META.STORE_REGISTRY R
  ON R.STORE_KEY = D.STORE_KEY;

-- 3. Published surfaces -------------------------------------------------------
--    Fixed names the shared monitoring, reconciliation, and BI read. Switching
--    to the native path replaces only these two views.
CREATE OR REPLACE VIEW SHOPIFY_CONTROL.META.V_DAILY_SHOP_ACTIVITY
COMMENT = 'Published contract surface. Openflow path implementation.'
AS
SELECT
  STORE_KEY, SHOP_URL, ACTIVITY_DATE, CURRENCY_CODE,
  ORDERS_PLACED, ORDERS_CANCELLED, UNITS_SOLD,
  GROSS_SALES, DISCOUNTS, REFUNDS, NET_SALES,
  SHIPMENTS_CREATED, SHIPMENTS_SUCCESS, SHIPMENTS_DELIVERED
FROM SHOPIFY_ANALYTICS.CORE.DAILY_SHOP_ACTIVITY;

CREATE OR REPLACE VIEW SHOPIFY_CONTROL.META.V_STORE_FRESHNESS
COMMENT = 'Published ops surface: hours since the newest order update per active store. Openflow path implementation.'
AS
SELECT
  R.STORE_KEY,
  R.SHOP_DOMAIN,
  R.BUSINESS_OWNER,
  R.CONNECTOR_INSTALLED_AT                                  AS PIPELINE_READY_AT,
  MAX(O.UPDATED_AT)                                         AS LAST_ORDER_UPDATE,
  DATEDIFF('hour', MAX(O.UPDATED_AT), CURRENT_TIMESTAMP())  AS HOURS_SINCE_LAST_UPDATE,
  COUNT(O.ORDER_ID)                                         AS ORDERS_LOADED
FROM SHOPIFY_CONTROL.META.STORE_REGISTRY R
LEFT JOIN SHOPIFY_ANALYTICS.CORE.ORDERS_ALL O
  ON O.STORE_KEY = R.STORE_KEY
WHERE R.IS_ACTIVE
GROUP BY R.STORE_KEY, R.SHOP_DOMAIN, R.BUSINESS_OWNER, R.CONNECTOR_INSTALLED_AT;

-- 4. Read access for analysts --------------------------------------------------
CREATE ROLE IF NOT EXISTS SHOPIFY_ANALYST
  COMMENT = 'Read-only access to the Shopify analytics layer';
GRANT USAGE  ON DATABASE SHOPIFY_ANALYTICS TO ROLE SHOPIFY_ANALYST;
GRANT USAGE  ON SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES    IN SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON ALL VIEWS             IN SCHEMA SHOPIFY_ANALYTICS.CORE TO ROLE SHOPIFY_ANALYST;
GRANT USAGE  ON WAREHOUSE SHOPIFY_ANALYTICS_WH TO ROLE SHOPIFY_ANALYST;
-- The published contract surface, so BI never hard-codes a path-specific name.
GRANT USAGE  ON DATABASE SHOPIFY_CONTROL      TO ROLE SHOPIFY_ANALYST;
GRANT USAGE  ON SCHEMA   SHOPIFY_CONTROL.META TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON VIEW SHOPIFY_CONTROL.META.V_DAILY_SHOP_ACTIVITY TO ROLE SHOPIFY_ANALYST;

-- 5. Verify -------------------------------------------------------------------
SELECT COUNT_IF(STATUS <> 'OK') AS CONTRACT_VIOLATIONS
FROM SHOPIFY_CONTROL.META.V_CONTRACT_CONFORMANCE;

SELECT NAME, TARGET_LAG, SCHEDULING_STATE, DATA_TIMESTAMP
FROM TABLE(SHOPIFY_ANALYTICS.INFORMATION_SCHEMA.DYNAMIC_TABLES())
ORDER BY NAME;

SELECT STORE_KEY, ACTIVITY_DATE, CURRENCY_CODE, ORDERS_PLACED, UNITS_SOLD,
       NET_SALES, SHIPMENTS_CREATED, SHIPMENTS_SUCCESS
FROM SHOPIFY_CONTROL.META.V_DAILY_SHOP_ACTIVITY
ORDER BY ACTIVITY_DATE DESC, STORE_KEY
LIMIT 50;
