/*=============================================================================
  04_workshop/07_verify_and_stop_triggered_task.sql
  Optional Exercise - Verify Triggered Execution and Stop Automation
  Pair-programmed by SE Community + Cortex Code | Expires: 2026-10-08
=============================================================================*/

USE ROLE SYSADMIN;
USE WAREHOUSE SFE_STREAMS_CDC_WH;
USE SCHEMA SNOWFLAKE_EXAMPLE.STREAMS_CDC_WORKSHOP;

WITH RECENT_RUNS AS (
  SELECT
    NAME,
    STATE,
    SCHEDULED_FROM,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    ERROR_CODE,
    ERROR_MESSAGE
  FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('minute', -10, CURRENT_TIMESTAMP()),
    SCHEDULED_TIME_RANGE_END => CURRENT_TIMESTAMP(),
    RESULT_LIMIT => 20,
    TASK_NAME => 'TASK_CONSUME_ORDER_CHANGES',
    DATABASE_NAME => 'SNOWFLAKE_EXAMPLE',
    SCHEMA_NAME => 'STREAMS_CDC_WORKSHOP'
  ))
),
ORDER_1007 AS (
  SELECT UPDATED_AT
  FROM CURRENT_ORDERS
  WHERE ORDER_ID = 1007
)
SELECT
  IFF(COUNT_IF(
    STATE = 'SUCCEEDED'
    AND SCHEDULED_FROM = 'TRIGGER'
    AND COMPLETED_TIME >= (SELECT UPDATED_AT FROM ORDER_1007)
  ) > 0, 'PASS', 'RETRY') AS TRIGGERED_RUN_SUCCEEDED,
  MAX_BY(STATE, SCHEDULED_TIME) AS LATEST_STATE,
  MAX(SCHEDULED_TIME) AS LATEST_SCHEDULED_TIME,
  MAX_BY(ERROR_MESSAGE, SCHEDULED_TIME) AS LATEST_ERROR
FROM RECENT_RUNS;

EXECUTE IMMEDIATE $$
BEGIN
  IF (EXISTS (
    SELECT ORDER_ID
    FROM CURRENT_ORDERS
    WHERE ORDER_ID = 1007
  ) AND NOT SYSTEM$STREAM_HAS_DATA('RAW_ORDERS_STREAM')) THEN
    ALTER TASK TASK_CONSUME_ORDER_CHANGES SUSPEND;
  END IF;
END;
$$;

SELECT
  (SELECT COUNT(*) FROM RAW_ORDERS) AS source_rows,
  (SELECT COUNT(*) FROM CURRENT_ORDERS) AS target_rows,
  (SELECT COUNT(*) FROM ORDER_CHANGE_AUDIT) AS cumulative_audit_rows,
  SYSTEM$STREAM_HAS_DATA('RAW_ORDERS_STREAM') AS stream_has_data,
  IFF(EXISTS (
    SELECT ORDER_ID
    FROM CURRENT_ORDERS
    WHERE ORDER_ID = 1007
  ), 'PASS', 'RETRY') AS ORDER_1007_APPLIED,
  IFF(SYSTEM$STREAM_HAS_DATA('RAW_ORDERS_STREAM'), 'Task remains resumed; wait and rerun script 07.', 'Task suspended after successful consumption.') AS task_action;
