/*==============================================================================
TEARDOWN ALL — Cortex AI Functions Cost Governance Toolkit
Pair-programmed by SE Community + Cortex Code | Expires: 2026-05-07

Drops all objects created by this tool in dependency order.
Does NOT drop shared infrastructure (SNOWFLAKE_EXAMPLE, SFE_GIT_API_INTEGRATION).
==============================================================================*/

USE ROLE SYSADMIN;
USE WAREHOUSE SFE_AI_SPEND_CONTROLS_WH;

-- 1. Suspend and drop tasks (must be suspended before drop)
ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.MONTHLY_AI_FUNCTIONS_ACCESS_REFRESH SUSPEND;
ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.MONITOR_RUNAWAY_AI_QUERIES SUSPEND;
ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.ENFORCE_AI_FUNCTIONS_LIMITS_TASK SUSPEND;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.MONTHLY_AI_FUNCTIONS_ACCESS_REFRESH;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.MONITOR_RUNAWAY_AI_QUERIES;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.ENFORCE_AI_FUNCTIONS_LIMITS_TASK;

-- 2. Suspend and drop alert
ALTER ALERT IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.AI_FUNCTIONS_MONTHLY_SPEND_ALERT SUSPEND;
DROP ALERT IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS.AI_FUNCTIONS_MONTHLY_SPEND_ALERT;

-- 3. Drop schema (cascades notebook, streamlit, procedures, tables)
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.AI_SPEND_CONTROLS CASCADE;

-- 4. Drop notification integration (requires ACCOUNTADMIN)
USE ROLE ACCOUNTADMIN;
DROP NOTIFICATION INTEGRATION IF EXISTS SFE_AI_COST_ALERTS;

-- 5. Drop role
DROP ROLE IF EXISTS AI_FUNCTIONS_USER_ROLE;

-- 6. Drop warehouse
USE ROLE SYSADMIN;
DROP WAREHOUSE IF EXISTS SFE_AI_SPEND_CONTROLS_WH;

SELECT 'Teardown complete — all Cortex AI Cost Governance objects removed.' AS status;
