/*
Snowflake MCP Role Controls - Dedicated access role
Pair-programmed by SE Community + Cortex Code

Run as a role that can create roles and grant the referenced privileges.
Replace the example object names with existing MCP resources before running.
*/

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS MCP_ACCESS_ROLE
  COMMENT = 'Least-privileged access role for the governed MCP server';

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER
  TO ROLE MCP_ACCESS_ROLE;

GRANT USAGE ON WAREHOUSE MCP_WAREHOUSE
  TO ROLE MCP_ACCESS_ROLE;

GRANT USAGE ON DATABASE MCP_DB
  TO ROLE MCP_ACCESS_ROLE;

GRANT USAGE ON SCHEMA MCP_DB.MCP_SCHEMA
  TO ROLE MCP_ACCESS_ROLE;

GRANT USAGE ON MCP SERVER MCP_DB.MCP_SCHEMA.BUSINESS_MCP
  TO ROLE MCP_ACCESS_ROLE;

GRANT USAGE ON AGENT MCP_DB.MCP_SCHEMA.BUSINESS_AGENT
  TO ROLE MCP_ACCESS_ROLE;

-- Grant only resources actually configured on the agent.
GRANT SELECT ON SEMANTIC VIEW MCP_DB.MCP_SCHEMA.BUSINESS_SEMANTIC_VIEW
  TO ROLE MCP_ACCESS_ROLE;

GRANT SELECT ON TABLE MCP_DB.MCP_SCHEMA.BUSINESS_FACTS
  TO ROLE MCP_ACCESS_ROLE;

GRANT USAGE ON CORTEX SEARCH SERVICE MCP_DB.MCP_SCHEMA.BUSINESS_SEARCH
  TO ROLE MCP_ACCESS_ROLE;

GRANT ROLE MCP_ACCESS_ROLE TO USER MCP_USER;

ALTER USER MCP_USER
  SET DEFAULT_ROLE = MCP_ACCESS_ROLE
      DEFAULT_WAREHOUSE = MCP_WAREHOUSE;
