/*==============================================================================
TEARDOWN ALL - Cortex Cost Intelligence v4.0
Pair-programmed by SE Community + Cortex Code

Complete cleanup of all Cortex Cost Intelligence objects.
Identical to sql/99_cleanup/cleanup_all.sql -- placed at project root
for consistency with the monorepo convention.
==============================================================================*/

USE ROLE ACCOUNTADMIN;

ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_DAILY_CORTEX_SNAPSHOT SUSPEND;
ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_HOURLY_BUDGET_CHECK SUSPEND;
ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_MONTHLY_ACCESS_RESTORE SUSPEND;
ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_HOURLY_RUNAWAY_DETECTION SUSPEND;
ALTER ALERT IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.ALERT_MONTHLY_CORTEX_SPEND SUSPEND;

DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.CORTEX_COST_INTELLIGENCE;

DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.SV_CORTEX_COST_INTELLIGENCE;

DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_COST_INTELLIGENCE_FLAT;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_USAGE_HISTORY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_COST_EXPORT;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_COST_FORECAST;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_COST_ANOMALIES_CURRENT;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_COST_ANOMALIES;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_DAILY_SUMMARY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_MODEL_EFFICIENCY;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_USER_SPEND_ATTRIBUTION;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_ANALYST_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_AI_FUNCTIONS_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_AGENT_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_SNOWFLAKE_INTELLIGENCE_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_CODE_CLI_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_SEARCH_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_SEARCH_SERVING_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_FUNCTIONS_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_FINE_TUNING_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_DOCUMENT_PROCESSING_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_REST_API_DETAIL;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.V_CORTEX_PROVISIONED_THROUGHPUT_DETAIL;

DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_DAILY_CORTEX_SNAPSHOT;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_HOURLY_BUDGET_CHECK;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_MONTHLY_ACCESS_RESTORE;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.TASK_HOURLY_RUNAWAY_DETECTION;
DROP ALERT IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.ALERT_MONTHLY_CORTEX_SPEND;

DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.PROC_SEND_MONTHLY_SPEND_ALERT(FLOAT);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.PROC_MONITOR_AND_CANCEL_RUNAWAY_QUERIES(NUMBER);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.PROC_GRANT_AI_ACCESS(VARCHAR, NUMBER);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.PROC_REVOKE_AI_ACCESS(VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.PROC_CHECK_USER_BUDGETS();
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.PROC_RESTORE_MONTHLY_ACCESS();

DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.CORTEX_ALERT_STATE;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.CORTEX_USER_BUDGETS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.CORTEX_USAGE_SNAPSHOTS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.REST_API_PRICING;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.CORTEX_USAGE_CONFIG;

DROP STREAMLIT IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE.CORTEX_COST_INTELLIGENCE_APP;

DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_COST_INTELLIGENCE;

SELECT 'Teardown complete' AS status;
