/*=============================================================================
  02_data/01_create_tables.sql
  Snowflake Streams CDC Workshop - Source, Target, and Audit Tables
  Pair-programmed by SE Community + Cortex Code | Expires: 2026-10-08
=============================================================================*/

USE ROLE SYSADMIN;
USE WAREHOUSE SFE_STREAMS_CDC_WH;
USE SCHEMA SNOWFLAKE_EXAMPLE.STREAMS_CDC_WORKSHOP;

CREATE OR REPLACE TABLE RAW_ORDERS (
  ORDER_ID NUMBER(10, 0) NOT NULL,
  CUSTOMER_ID NUMBER(10, 0) NOT NULL,
  ORDER_STATUS VARCHAR(20) NOT NULL,
  ORDER_TOTAL NUMBER(12, 2) NOT NULL,
  ORDER_TS TIMESTAMP_NTZ(6) NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ(6) NOT NULL,
  CONSTRAINT PK_RAW_ORDERS PRIMARY KEY (ORDER_ID)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
  COMMENT = 'DEMO: Simulated operational orders with one-day Time Travel retention (Expires: 2026-10-08)';

CREATE OR REPLACE TABLE CURRENT_ORDERS (
  ORDER_ID NUMBER(10, 0) NOT NULL,
  CUSTOMER_ID NUMBER(10, 0) NOT NULL,
  ORDER_STATUS VARCHAR(20) NOT NULL,
  ORDER_TOTAL NUMBER(12, 2) NOT NULL,
  ORDER_TS TIMESTAMP_NTZ(6) NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ(6) NOT NULL,
  CDC_APPLIED_AT TIMESTAMP_LTZ(6) NOT NULL,
  CONSTRAINT PK_CURRENT_ORDERS PRIMARY KEY (ORDER_ID)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
  COMMENT = 'DEMO: Current order state maintained from the Stream (Expires: 2026-10-08)';

CREATE OR REPLACE TABLE ORDER_CHANGE_AUDIT (
  BATCH_ID VARCHAR(36) NOT NULL,
  ORDER_ID NUMBER(10, 0) NOT NULL,
  CUSTOMER_ID NUMBER(10, 0) NOT NULL,
  ORDER_STATUS VARCHAR(20) NOT NULL,
  ORDER_TOTAL NUMBER(12, 2) NOT NULL,
  ORDER_TS TIMESTAMP_NTZ(6) NOT NULL,
  UPDATED_AT TIMESTAMP_NTZ(6) NOT NULL,
  CDC_ACTION VARCHAR(6) NOT NULL,
  CDC_IS_UPDATE BOOLEAN NOT NULL,
  CDC_ROW_ID VARCHAR NOT NULL,
  PROCESSED_AT TIMESTAMP_LTZ(6) NOT NULL
)
  DATA_RETENTION_TIME_IN_DAYS = 1
  COMMENT = 'DEMO: Durable evidence of every consumed net CDC row (Expires: 2026-10-08)';
