-- ============================================================================
-- demo-cortex-ai-cost-controls: Teardown
-- Pair-programmed by SE Community + Cortex Code
-- ============================================================================

USE ROLE SYSADMIN;

-- Suspend and drop task
ALTER TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.TASK_REFRESH_COST_MATERIALIZATION SUSPEND;
DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.TASK_REFRESH_COST_MATERIALIZATION;

-- Drop materialized tables
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.MAT_AI_USAGE_UNIFIED;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.MAT_AI_SPEND_DAILY;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.MAT_AI_SPEND_BY_USER;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.MAT_AGENT_ATTRIBUTION;

-- Drop procedure
DROP PROCEDURE IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.SP_REFRESH_COST_MATERIALIZATION();

-- Drop quota (requires appropriate role)
BEGIN
    DROP SNOWFLAKE.CORE.QUOTA IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS.AI_COST_QUOTA;
EXCEPTION
    WHEN OTHER THEN NULL;
END;

-- Drop schema
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.CORTEX_AI_COST_CONTROLS;

-- Drop warehouse
DROP WAREHOUSE IF EXISTS SFE_CORTEX_AI_COST_CONTROLS_WH;

-- Note: Does NOT drop SNOWFLAKE_EXAMPLE database (shared across demos).
-- Note: Teardown the React app separately: snow app teardown

SELECT 'Teardown complete. Run "snow app teardown" to remove the React app.' AS status;
