/*==============================================================================
  99_cleanup/teardown.sql
  Media Campaign Analytics — Drop All Project Objects
  Pair-programmed by SE Community + Cortex Code
==============================================================================*/

USE ROLE SYSADMIN;

-- Agent
DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.MEDIA_CAMPAIGN_AGENT;

-- Cortex Search Service
DROP CORTEX SEARCH SERVICE IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.CAMPAIGN_DOCS_SEARCH;

-- Semantic view
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_MEDIA_CAMPAIGN_ANALYTICS;

-- Views and tables
DROP VIEW   IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.V_CAMPAIGN_KPI;
DROP TABLE  IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.DOC_CAMPAIGN_CONTENT;
DROP TABLE  IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.FACT_DAILY_PERFORMANCE;
DROP TABLE  IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.DIM_CAMPAIGN;
DROP TABLE  IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.DIM_CHANNEL;
DROP TABLE  IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS.DIM_CLIENT;

-- Project schema and warehouse
DROP SCHEMA    IF EXISTS SNOWFLAKE_EXAMPLE.MEDIA_CAMPAIGN_ANALYTICS;
DROP WAREHOUSE IF EXISTS SFE_MEDIA_CAMPAIGN_WH;

-- NOTE: Do NOT drop the following shared infrastructure:
--   SNOWFLAKE_EXAMPLE (database)
--   SNOWFLAKE_EXAMPLE.GIT_REPOS (schema)
--   SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS (schema — shared with other demos)
--   SNOWFLAKE_EXAMPLE.GIT_REPOS.SFE_DEMOS_REPO (used by all monorepo demos)
--   SFE_GIT_API_INTEGRATION (account-level, shared)
