CREATE OR REPLACE STREAMLIT CORTEX_AGENT_COST_APP
  FROM '@SNOWFLAKE_EXAMPLE.GIT_REPOS.SFE_DEMOS_REPO/branches/main/tool-cortex-agent-cost/streamlit/cortex_agent_cost/'
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = SFE_CORTEX_AGENT_COST_WH
  COMMENT = 'TOOL: Cortex Agent Cost Dashboard (Expires: 2026-04-22)'
  TITLE = 'Cortex Agent Cost';

ALTER STREAMLIT CORTEX_AGENT_COST_APP ADD LIVE VERSION FROM LAST;

GRANT USAGE ON STREAMLIT CORTEX_AGENT_COST_APP TO ROLE PUBLIC;
