/*==============================================================================
TEARDOWN ALL - Governed GitHub Integration for Cortex Code
Pair-programmed by SE Community + Cortex Code
INSTRUCTIONS: Open in Snowsight -> Click "Run All"
==============================================================================*/

USE ROLE ACCOUNTADMIN;

DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.GOVERNANCE_ADVISOR;

DROP FUNCTION IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.VALIDATE_GOVERNANCE_POLICY(VARCHAR);

DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.MCP_CONNECTION_AUDIT;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB.GOVERNANCE_POLICY_LOG;

DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.COCO_GOVERNANCE_GITHUB;

DROP WAREHOUSE IF EXISTS SFE_COCO_GOVERNANCE_GITHUB_WH;

SELECT 'Teardown complete!' AS status, CURRENT_TIMESTAMP() AS completed_at;
