USE DATABASE SNOWFLAKE_EXAMPLE;
USE SCHEMA IOT_LIFECYCLE;
USE WAREHOUSE SFE_IOT_LIFECYCLE_WH;

CREATE STREAMLIT IF NOT EXISTS IOT_LIFECYCLE_DASHBOARD
  FROM '@SNOWFLAKE_EXAMPLE.GIT_REPOS.SFE_DEMOS_REPO/branches/main/demo-iot-lifecycle/streamlit'
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = SFE_IOT_LIFECYCLE_WH
  TITLE = 'IoT Lifecycle Dashboard'
  COMMENT = 'DEMO: Fleet map, RFID tracking, CFO chat (Expires: 2026-06-11)';

GRANT USAGE ON STREAMLIT SNOWFLAKE_EXAMPLE.IOT_LIFECYCLE.IOT_LIFECYCLE_DASHBOARD TO ROLE PUBLIC;
