-- ============================================================================
-- Script: sql/99_cleanup/teardown_all.sql
-- Purpose: Remove demo objects created in the DATA_QUALITY project.
-- Target: SNOWFLAKE_EXAMPLE.DATA_QUALITY schema objects, SFE_DATA_QUALITY_WH, repo stage.
-- Deps: None (safe to run with IF EXISTS).
-- ============================================================================

DROP STREAMLIT IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.DATA_QUALITY_DASHBOARD;

DROP TASK IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.refresh_data_quality_metrics_task;

DROP STREAM IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.RAW_ATHLETE_PERFORMANCE_STREAM;
DROP STREAM IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.RAW_FAN_ENGAGEMENT_STREAM;

DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.V_QUALITY_SCORE_TREND;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.V_DATA_QUALITY_METRICS;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.V_FAN_ENGAGEMENT;
DROP VIEW IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.V_ATHLETE_PERFORMANCE;

DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.STG_DATA_QUALITY_METRICS;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.RAW_FAN_ENGAGEMENT;
DROP TABLE IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY.RAW_ATHLETE_PERFORMANCE;

DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.DATA_QUALITY CASCADE;
DROP WAREHOUSE IF EXISTS SFE_DATA_QUALITY_WH;
DROP GIT REPOSITORY IF EXISTS SNOWFLAKE_EXAMPLE.GIT_REPOS.SFE_DATA_QUALITY_REPO;
