/*==============================================================================
TEARDOWN ALL - Glaze & Classify
WARNING: This will DELETE all demo objects. Cannot be undone.
==============================================================================*/

USE ROLE SYSADMIN;

-- Drop Streamlit app
DROP STREAMLIT IF EXISTS SNOWFLAKE_EXAMPLE.GLAZE_AND_CLASSIFY.GLAZE_CLASSIFY_DASHBOARD;

-- Drop Intelligence agent
DROP AGENT IF EXISTS SNOWFLAKE_EXAMPLE.GLAZE_AND_CLASSIFY.GLAZE_CLASSIFIER_AGENT;

-- Drop semantic view (in SEMANTIC_MODELS schema)
DROP SEMANTIC VIEW IF EXISTS SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_GLAZE_PRODUCTS;

-- Drop SPCS service and function
DROP FUNCTION IF EXISTS SNOWFLAKE_EXAMPLE.GLAZE_AND_CLASSIFY.CLASSIFY_IMAGE(VARCHAR);
DROP SERVICE IF EXISTS SNOWFLAKE_EXAMPLE.GLAZE_AND_CLASSIFY.GLAZE_VISION_SERVICE;
DROP COMPUTE POOL IF EXISTS SFE_GLAZE_VISION_POOL;

-- Drop project schema (CASCADE removes all tables, views, etc.)
DROP SCHEMA IF EXISTS SNOWFLAKE_EXAMPLE.GLAZE_AND_CLASSIFY CASCADE;

-- Drop project warehouse
DROP WAREHOUSE IF EXISTS SFE_GLAZE_AND_CLASSIFY_WH;

-- Drop Git repository
DROP GIT REPOSITORY IF EXISTS SNOWFLAKE_EXAMPLE.TOOLS.SFE_GLAZE_AND_CLASSIFY_REPO;

-- PROTECTED - NEVER DROP:
-- SNOWFLAKE_EXAMPLE database
-- SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS schema
-- SNOWFLAKE_EXAMPLE.TOOLS schema
-- SFE_GIT_API_INTEGRATION

SELECT 'Glaze & Classify teardown complete!' AS status;
