/*==============================================================================
06 - Roles and Grants
Pair-programmed by SE Community + Cortex Code | Expires: 2026-04-02

Two roles demonstrate tiered access:
  TV_VIEWER_ROLE  - Low auth: read schedules, search KB, limited viewership
  TV_ADMIN_ROLE   - Full auth: everything including member data and full metrics
==============================================================================*/

USE ROLE ACCOUNTADMIN;

-- Viewer role (low-auth tier)
CREATE ROLE IF NOT EXISTS TV_VIEWER_ROLE
  COMMENT = 'DEMO: TV network viewer access (Expires: 2026-04-02)';

GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE TV_VIEWER_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.AGENT_MULTICONTEXT TO ROLE TV_VIEWER_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS TO ROLE TV_VIEWER_ROLE;
GRANT USAGE ON WAREHOUSE SFE_AGENT_MULTICONTEXT_WH TO ROLE TV_VIEWER_ROLE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.AGENT_MULTICONTEXT.STATION_INFO TO ROLE TV_VIEWER_ROLE;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.AGENT_MULTICONTEXT.PROGRAMMING_SCHEDULE TO ROLE TV_VIEWER_ROLE;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.AGENT_MULTICONTEXT.SUPPORT_ARTICLES TO ROLE TV_VIEWER_ROLE;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.AGENT_MULTICONTEXT.VIEWERSHIP_METRICS TO ROLE TV_VIEWER_ROLE;
GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.AGENT_MULTICONTEXT.USER_STATION_MAPPING TO ROLE TV_VIEWER_ROLE;

GRANT SELECT ON SEMANTIC VIEW SNOWFLAKE_EXAMPLE.SEMANTIC_MODELS.SV_AGENT_MULTICONTEXT_VIEWERSHIP
  TO ROLE TV_VIEWER_ROLE;

-- Admin role (full-auth tier) inherits viewer and adds member data
CREATE ROLE IF NOT EXISTS TV_ADMIN_ROLE
  COMMENT = 'DEMO: TV network admin access (Expires: 2026-04-02)';

GRANT ROLE TV_VIEWER_ROLE TO ROLE TV_ADMIN_ROLE;

GRANT SELECT ON TABLE SNOWFLAKE_EXAMPLE.AGENT_MULTICONTEXT.MEMBER_ACCOUNTS TO ROLE TV_ADMIN_ROLE;

-- Grant roles to SYSADMIN for administration
GRANT ROLE TV_VIEWER_ROLE TO ROLE SYSADMIN;
GRANT ROLE TV_ADMIN_ROLE TO ROLE SYSADMIN;
