/*
  guide-shopify-multistore-snowflake — sql/native/01_landing.sql
  Pair-programmed by SE Community + Cortex Code
  Expires: 2026-12-21

  PURPOSE
    The native path's landing layer: pipeline role, warehouse, internal stage,
    file format, run log, qualification evidence, and the single raw VARIANT
    table that holds every store.

  WHY ONE RAW TABLE
    The pull procedure writes STORE_KEY on every row, so all stores share one
    STORE_KEY-partitioned table and the analytics layer is static SQL. This is
    the structural difference from the Openflow path, which gets one schema per
    store from the connector and therefore needs a generated UNION ALL.
    Same contract out, different SQL to get there.

  PREREQUISITE
    sql/shared/01_store_registry.sql has been run. The store registry and the
    reconciliation baseline are shared objects and are NOT created here.

  RUN AS      ACCOUNTADMIN, then SHOPIFY_PIPELINE_RL
  RUNTIME     < 1 minute
*/

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SHOPIFY_PIPELINE_RL
  COMMENT = 'Owns the deterministic Shopify ingestion pipeline';
GRANT ROLE SHOPIFY_PIPELINE_RL TO ROLE SYSADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SHOPIFY_PIPELINE_RL;

CREATE DATABASE IF NOT EXISTS SHOPIFY_NATIVE;
CREATE SCHEMA IF NOT EXISTS SHOPIFY_NATIVE.CONTROL;
CREATE SCHEMA IF NOT EXISTS SHOPIFY_NATIVE.LANDING;
CREATE SCHEMA IF NOT EXISTS SHOPIFY_NATIVE.ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS SHOPIFY_PIPELINE_WH
  WAREHOUSE_SIZE               = 'XSMALL'
  AUTO_SUSPEND                 = 60
  AUTO_RESUME                  = TRUE
  INITIALLY_SUSPENDED          = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 7200
  COMMENT = 'Daily Shopify Bulk API pull, COPY, and Dynamic Table refresh';

GRANT USAGE, OPERATE ON WAREHOUSE SHOPIFY_PIPELINE_WH TO ROLE SHOPIFY_PIPELINE_RL;

GRANT OWNERSHIP ON DATABASE SHOPIFY_NATIVE           TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SHOPIFY_NATIVE.CONTROL     TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SHOPIFY_NATIVE.LANDING     TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SHOPIFY_NATIVE.ANALYTICS   TO ROLE SHOPIFY_PIPELINE_RL COPY CURRENT GRANTS;

-- Access to the shared control plane. The pipeline role reads the registry to
-- decide which stores to pull, updates qualification status, and creates the
-- two published contract views.
GRANT USAGE  ON DATABASE SHOPIFY_CONTROL      TO ROLE SHOPIFY_PIPELINE_RL;
GRANT USAGE  ON SCHEMA   SHOPIFY_CONTROL.META TO ROLE SHOPIFY_PIPELINE_RL;
GRANT SELECT ON ALL TABLES IN SCHEMA SHOPIFY_CONTROL.META TO ROLE SHOPIFY_PIPELINE_RL;
GRANT SELECT ON ALL VIEWS  IN SCHEMA SHOPIFY_CONTROL.META TO ROLE SHOPIFY_PIPELINE_RL;
GRANT CREATE VIEW          ON SCHEMA SHOPIFY_CONTROL.META TO ROLE SHOPIFY_PIPELINE_RL;
GRANT UPDATE ON TABLE SHOPIFY_CONTROL.META.STORE_REGISTRY TO ROLE SHOPIFY_PIPELINE_RL;

USE ROLE SHOPIFY_PIPELINE_RL;

CREATE STAGE IF NOT EXISTS SHOPIFY_NATIVE.LANDING.SHOPIFY_STAGE
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Immutable JSONL results from Shopify Bulk Operations';

CREATE FILE FORMAT IF NOT EXISTS SHOPIFY_NATIVE.LANDING.JSONL_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

-- Run log: one row per store per object per attempt. The only place a failed
-- bulk operation ID survives, which is what makes diagnosis possible.
CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.CONTROL.PULL_RUN_LOG (
  RUN_ID            VARCHAR(36) NOT NULL,
  STORE_KEY         VARCHAR(64) NOT NULL,
  OBJECT_NAME       VARCHAR(64) NOT NULL,
  STARTED_AT        TIMESTAMP_TZ NOT NULL,
  COMPLETED_AT      TIMESTAMP_TZ,
  STATUS            VARCHAR(32) NOT NULL,
  BULK_OPERATION_ID VARCHAR,
  FILE_NAME         VARCHAR,
  OBJECT_COUNT      NUMBER,
  ROWS_LOADED       NUMBER,
  WATERMARK_FROM    TIMESTAMP_TZ,
  WATERMARK_TO      TIMESTAMP_TZ,
  ERROR_CLASS       VARCHAR,
  ERROR_MESSAGE     VARCHAR,
  QUERY_ID          VARCHAR
);

CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.CONTROL.QUALIFICATION_RESULTS (
  STORE_KEY  VARCHAR(64) NOT NULL,
  GATE_NAME  VARCHAR(64) NOT NULL,
  PASSED     BOOLEAN     NOT NULL,
  EVIDENCE   VARIANT,
  CHECKED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- One raw table for every store and object. CHANGE_TRACKING lets the Dynamic
-- Tables refresh incrementally.
CREATE TABLE IF NOT EXISTS SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW (
  STORE_KEY         VARCHAR(64) NOT NULL,
  OBJECT_NAME       VARCHAR(64) NOT NULL,
  PULLED_AT         TIMESTAMP_TZ NOT NULL,
  SOURCE_FILE       VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER NOT NULL,
  RECORD            VARIANT NOT NULL,
  LOADED_AT         TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE;

-- Verify
SHOW TABLES IN SCHEMA SHOPIFY_NATIVE.CONTROL;
SELECT STORE_KEY, SHOP_DOMAIN, IS_ACTIVE, QUALIFICATION_STATUS, CREDENTIAL_OBJECT_FQN
FROM SHOPIFY_CONTROL.META.STORE_REGISTRY
ORDER BY STORE_KEY;
