/*
  guide-shopify-multistore-snowflake — sql/native/05_analytics_layer.sql
  Pair-programmed by SE Community + Cortex Code
  Expires: 2026-12-21

  PURPOSE
    Typed Dynamic Tables over the single raw VARIANT table, ending in the shared
    analytics contract.

  CONTRACT
    The column list, grain, and every measure definition are specified once in
    README.md ("The one analytics contract") and encoded in
    SHOPIFY_CONTROL.META.CONTRACT_COLUMNS. The Openflow path produces the same
    14 columns from different SQL: it generates a UNION ALL across per-store
    schemas, because its connector writes one schema per store. This path is
    static SQL over one STORE_KEY-partitioned table. Same output, different SQL.

    After deploying, verify:
      SELECT COUNT_IF(STATUS <> 'OK') FROM SHOPIFY_CONTROL.META.V_CONTRACT_CONFORMANCE;

  ORDER-INDEPENDENCE
    Object grouping is OFF by default for bulkOperationRunQuery on API 2026-01
    and later, so a child record does not reliably follow its parent in the
    JSONL. Every child table below joins to its parent by __parentId within the
    same SOURCE_FILE. Nothing here depends on row order.

  CHANGING THE CONTRACT ON A LIVE DEPLOYMENT
    CREATE OR ALTER DYNAMIC TABLE accepts a limited set of changes. If it
    rejects a column-list change, DROP the affected Dynamic Table and re-run
    this file; the raw table is the system of record, so nothing is lost.

  RUN AS      SHOPIFY_PIPELINE_RL
  SOURCE      https://docs.snowflake.com/en/user-guide/dynamic-tables/overview
*/

USE ROLE SHOPIFY_PIPELINE_RL;
USE WAREHOUSE SHOPIFY_PIPELINE_WH;

-- 1. Orders --------------------------------------------------------------------
CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.ORDERS (
  STORE_KEY VARCHAR,
  ORDER_ID VARCHAR,
  ORDER_NAME VARCHAR,
  CREATED_AT TIMESTAMP_TZ,
  UPDATED_AT TIMESTAMP_TZ,
  PROCESSED_AT TIMESTAMP_TZ,
  CANCELLED_AT TIMESTAMP_TZ,
  FINANCIAL_STATUS VARCHAR,
  FULFILLMENT_STATUS VARCHAR,
  CURRENCY_CODE VARCHAR,
  IS_TEST BOOLEAN,
  TOTAL_PRICE NUMBER(38,4),
  TOTAL_DISCOUNTS NUMBER(38,4),
  TOTAL_REFUNDED NUMBER(38,4),
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_TZ
)
  TARGET_LAG = '24 hours'
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
SELECT
  STORE_KEY,
  RECORD:id::VARCHAR AS ORDER_ID,
  RECORD:name::VARCHAR AS ORDER_NAME,
  TRY_TO_TIMESTAMP_TZ(RECORD:createdAt::VARCHAR) AS CREATED_AT,
  TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) AS UPDATED_AT,
  TRY_TO_TIMESTAMP_TZ(RECORD:processedAt::VARCHAR) AS PROCESSED_AT,
  TRY_TO_TIMESTAMP_TZ(RECORD:cancelledAt::VARCHAR) AS CANCELLED_AT,
  RECORD:displayFinancialStatus::VARCHAR AS FINANCIAL_STATUS,
  RECORD:displayFulfillmentStatus::VARCHAR AS FULFILLMENT_STATUS,
  RECORD:currencyCode::VARCHAR AS CURRENCY_CODE,
  COALESCE(RECORD:test::BOOLEAN, FALSE) AS IS_TEST,
  TRY_TO_DECIMAL(RECORD:totalPriceSet:shopMoney:amount::VARCHAR, 38, 4) AS TOTAL_PRICE,
  TRY_TO_DECIMAL(RECORD:totalDiscountsSet:shopMoney:amount::VARCHAR, 38, 4) AS TOTAL_DISCOUNTS,
  TRY_TO_DECIMAL(RECORD:totalRefundedSet:shopMoney:amount::VARCHAR, 38, 4) AS TOTAL_REFUNDED,
  SOURCE_FILE,
  LOADED_AT
FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW
WHERE OBJECT_NAME = 'ORDERS'
  AND RECORD:id::VARCHAR LIKE 'gid://shopify/Order/%'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY STORE_KEY, RECORD:id::VARCHAR
  ORDER BY TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) DESC NULLS LAST, LOADED_AT DESC
) = 1;

-- 2. Order line items ----------------------------------------------------------
CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.ORDER_LINE_ITEMS (
  STORE_KEY VARCHAR,
  LINE_ITEM_ID VARCHAR,
  ORDER_ID VARCHAR,
  TITLE VARCHAR,
  SKU VARCHAR,
  VENDOR VARCHAR,
  QUANTITY NUMBER,
  CURRENT_QUANTITY NUMBER,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_TZ
)
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
WITH LATEST_ORDER_FILES AS (
  SELECT STORE_KEY, RECORD:id::VARCHAR AS ORDER_ID, SOURCE_FILE
  FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW
  WHERE OBJECT_NAME = 'ORDERS'
    AND RECORD:id::VARCHAR LIKE 'gid://shopify/Order/%'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_KEY, RECORD:id::VARCHAR
    ORDER BY TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) DESC NULLS LAST, LOADED_AT DESC
  ) = 1
)
SELECT
  R.STORE_KEY,
  R.RECORD:id::VARCHAR AS LINE_ITEM_ID,
  R.RECORD:__parentId::VARCHAR AS ORDER_ID,
  R.RECORD:title::VARCHAR AS TITLE,
  R.RECORD:sku::VARCHAR AS SKU,
  R.RECORD:vendor::VARCHAR AS VENDOR,
  TRY_TO_NUMBER(R.RECORD:quantity::VARCHAR) AS QUANTITY,
  TRY_TO_NUMBER(R.RECORD:currentQuantity::VARCHAR) AS CURRENT_QUANTITY,
  R.SOURCE_FILE,
  R.LOADED_AT
FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW R
JOIN LATEST_ORDER_FILES L
  ON L.STORE_KEY = R.STORE_KEY
 AND L.ORDER_ID = R.RECORD:__parentId::VARCHAR
 AND L.SOURCE_FILE = R.SOURCE_FILE
WHERE R.OBJECT_NAME = 'ORDERS'
  AND R.RECORD:id::VARCHAR LIKE 'gid://shopify/LineItem/%'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY R.STORE_KEY, R.RECORD:id::VARCHAR
  ORDER BY R.LOADED_AT DESC
) = 1;

-- 3. Order fulfillments (shipments) --------------------------------------------
CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.ORDER_FULFILLMENTS (
  STORE_KEY VARCHAR,
  FULFILLMENT_ID VARCHAR,
  ORDER_ID VARCHAR,
  STATUS VARCHAR,
  CREATED_AT TIMESTAMP_TZ,
  UPDATED_AT TIMESTAMP_TZ,
  DELIVERED_AT TIMESTAMP_TZ,
  SOURCE_FILE VARCHAR,
  LOADED_AT TIMESTAMP_TZ
)
  TARGET_LAG = DOWNSTREAM
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
WITH LATEST_ORDER_FILES AS (
  SELECT STORE_KEY, RECORD:id::VARCHAR AS ORDER_ID, SOURCE_FILE
  FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW
  WHERE OBJECT_NAME = 'ORDERS'
    AND RECORD:id::VARCHAR LIKE 'gid://shopify/Order/%'
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_KEY, RECORD:id::VARCHAR
    ORDER BY TRY_TO_TIMESTAMP_TZ(RECORD:updatedAt::VARCHAR) DESC NULLS LAST, LOADED_AT DESC
  ) = 1
)
SELECT
  R.STORE_KEY,
  R.RECORD:id::VARCHAR AS FULFILLMENT_ID,
  R.RECORD:__parentId::VARCHAR AS ORDER_ID,
  R.RECORD:status::VARCHAR AS STATUS,
  TRY_TO_TIMESTAMP_TZ(R.RECORD:createdAt::VARCHAR) AS CREATED_AT,
  TRY_TO_TIMESTAMP_TZ(R.RECORD:updatedAt::VARCHAR) AS UPDATED_AT,
  TRY_TO_TIMESTAMP_TZ(R.RECORD:deliveredAt::VARCHAR) AS DELIVERED_AT,
  R.SOURCE_FILE,
  R.LOADED_AT
FROM SHOPIFY_NATIVE.LANDING.SHOPIFY_RAW R
JOIN LATEST_ORDER_FILES L
  ON L.STORE_KEY = R.STORE_KEY
 AND L.ORDER_ID = R.RECORD:__parentId::VARCHAR
 AND L.SOURCE_FILE = R.SOURCE_FILE
WHERE R.OBJECT_NAME = 'ORDERS'
  AND R.RECORD:id::VARCHAR LIKE 'gid://shopify/Fulfillment/%'
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY R.STORE_KEY, R.RECORD:id::VARCHAR
  ORDER BY TRY_TO_TIMESTAMP_TZ(R.RECORD:updatedAt::VARCHAR) DESC NULLS LAST, R.LOADED_AT DESC
) = 1;

-- 4. DAILY_SHOP_ACTIVITY: the contract ----------------------------------------
--    Grain: (STORE_KEY, ACTIVITY_DATE, CURRENCY_CODE). See README.md.
--
--    Join notes, because both are load-bearing:
--
--    * SHIPMENT_DAILY LEFT JOINs ORDERS only to obtain the order's currency, so
--      a shipment whose parent order is outside the loaded window still counts,
--      with a NULL CURRENCY_CODE. An inner join would silently drop it.
--
--    * ORDER_DAILY FULL OUTER JOINs SHIPMENT_DAILY. A LEFT JOIN would drop
--      every day that had shipments but no orders processed -- routine whenever
--      orders placed on Monday ship on Wednesday and Wednesday had no new
--      orders. Those are real days with real shipment counts.
--
--    * CURRENCY_CODE is in the join predicate. Without it, one shipment row
--      fans out across every currency row for a multi-currency store.
--
--    * GROUP BY uses the full expression, never the ACTIVITY_DATE alias: an
--      alias there can resolve to a same-named column on the joined table.
--
--    All measures are COALESCEd to 0: a row exists only when there was order or
--    shipment activity, so "no orders" genuinely means zero, not unknown.
CREATE OR ALTER DYNAMIC TABLE SHOPIFY_NATIVE.ANALYTICS.DAILY_SHOP_ACTIVITY (
  STORE_KEY VARCHAR,
  SHOP_URL VARCHAR,
  ACTIVITY_DATE DATE,
  CURRENCY_CODE VARCHAR,
  ORDERS_PLACED NUMBER,
  ORDERS_CANCELLED NUMBER,
  UNITS_SOLD NUMBER,
  GROSS_SALES NUMBER(38,4),
  DISCOUNTS NUMBER(38,4),
  REFUNDS NUMBER(38,4),
  NET_SALES NUMBER(38,4),
  SHIPMENTS_CREATED NUMBER,
  SHIPMENTS_SUCCESS NUMBER,
  SHIPMENTS_DELIVERED NUMBER
)
  TARGET_LAG = '24 hours'
  WAREHOUSE = SHOPIFY_PIPELINE_WH
  REFRESH_MODE = ADAPTIVE
  INITIALIZE = ON_SCHEDULE
AS
WITH ORDER_DAILY AS (
  SELECT
    STORE_KEY,
    TO_DATE(CONVERT_TIMEZONE('UTC', PROCESSED_AT)) AS ACTIVITY_DATE,
    CURRENCY_CODE,
    COUNT(*)                                       AS ORDERS_PLACED,
    COUNT_IF(CANCELLED_AT IS NOT NULL)             AS ORDERS_CANCELLED,
    SUM(TOTAL_PRICE)                               AS GROSS_SALES,
    SUM(TOTAL_DISCOUNTS)                           AS DISCOUNTS,
    SUM(TOTAL_REFUNDED)                            AS REFUNDS,
    SUM(TOTAL_PRICE) - SUM(TOTAL_REFUNDED)         AS NET_SALES
  FROM SHOPIFY_NATIVE.ANALYTICS.ORDERS
  WHERE NOT IS_TEST
    AND PROCESSED_AT IS NOT NULL
  GROUP BY STORE_KEY, TO_DATE(CONVERT_TIMEZONE('UTC', PROCESSED_AT)), CURRENCY_CODE
),
UNIT_DAILY AS (
  SELECT
    O.STORE_KEY,
    TO_DATE(CONVERT_TIMEZONE('UTC', O.PROCESSED_AT)) AS ACTIVITY_DATE,
    O.CURRENCY_CODE,
    SUM(L.QUANTITY) AS UNITS_SOLD
  FROM SHOPIFY_NATIVE.ANALYTICS.ORDERS O
  JOIN SHOPIFY_NATIVE.ANALYTICS.ORDER_LINE_ITEMS L
    ON L.STORE_KEY = O.STORE_KEY
   AND L.ORDER_ID  = O.ORDER_ID
  WHERE NOT O.IS_TEST
    AND O.PROCESSED_AT IS NOT NULL
  GROUP BY O.STORE_KEY, TO_DATE(CONVERT_TIMEZONE('UTC', O.PROCESSED_AT)), O.CURRENCY_CODE
),
SHIPMENT_DAILY AS (
  SELECT
    F.STORE_KEY,
    TO_DATE(CONVERT_TIMEZONE('UTC', F.CREATED_AT)) AS ACTIVITY_DATE,
    O.CURRENCY_CODE,
    COUNT(*)                                       AS SHIPMENTS_CREATED,
    COUNT_IF(F.STATUS = 'SUCCESS')                 AS SHIPMENTS_SUCCESS,
    COUNT_IF(F.DELIVERED_AT IS NOT NULL)           AS SHIPMENTS_DELIVERED
  FROM SHOPIFY_NATIVE.ANALYTICS.ORDER_FULFILLMENTS F
  LEFT JOIN SHOPIFY_NATIVE.ANALYTICS.ORDERS O
    ON O.STORE_KEY = F.STORE_KEY
   AND O.ORDER_ID  = F.ORDER_ID
  -- Orphan shipments keep a NULL IS_TEST and survive; test-order shipments do not.
  WHERE NOT COALESCE(O.IS_TEST, FALSE)
  GROUP BY F.STORE_KEY, TO_DATE(CONVERT_TIMEZONE('UTC', F.CREATED_AT)), O.CURRENCY_CODE
),
DAY_FRAME AS (
  SELECT
    COALESCE(O.STORE_KEY,     S.STORE_KEY)     AS STORE_KEY,
    COALESCE(O.ACTIVITY_DATE, S.ACTIVITY_DATE) AS ACTIVITY_DATE,
    COALESCE(O.CURRENCY_CODE, S.CURRENCY_CODE) AS CURRENCY_CODE,
    COALESCE(O.ORDERS_PLACED,       0)         AS ORDERS_PLACED,
    COALESCE(O.ORDERS_CANCELLED,    0)         AS ORDERS_CANCELLED,
    COALESCE(O.GROSS_SALES,         0)         AS GROSS_SALES,
    COALESCE(O.DISCOUNTS,           0)         AS DISCOUNTS,
    COALESCE(O.REFUNDS,             0)         AS REFUNDS,
    COALESCE(O.NET_SALES,           0)         AS NET_SALES,
    COALESCE(S.SHIPMENTS_CREATED,   0)         AS SHIPMENTS_CREATED,
    COALESCE(S.SHIPMENTS_SUCCESS,   0)         AS SHIPMENTS_SUCCESS,
    COALESCE(S.SHIPMENTS_DELIVERED, 0)         AS SHIPMENTS_DELIVERED
  FROM ORDER_DAILY O
  FULL OUTER JOIN SHIPMENT_DAILY S
    ON S.STORE_KEY     = O.STORE_KEY
   AND S.ACTIVITY_DATE = O.ACTIVITY_DATE
   AND S.CURRENCY_CODE = O.CURRENCY_CODE
)
SELECT
  D.STORE_KEY,
  R.SHOP_DOMAIN             AS SHOP_URL,
  D.ACTIVITY_DATE,
  D.CURRENCY_CODE,
  D.ORDERS_PLACED,
  D.ORDERS_CANCELLED,
  COALESCE(U.UNITS_SOLD, 0) AS UNITS_SOLD,
  D.GROSS_SALES,
  D.DISCOUNTS,
  D.REFUNDS,
  D.NET_SALES,
  D.SHIPMENTS_CREATED,
  D.SHIPMENTS_SUCCESS,
  D.SHIPMENTS_DELIVERED
FROM DAY_FRAME D
LEFT JOIN UNIT_DAILY U
  ON U.STORE_KEY     = D.STORE_KEY
 AND U.ACTIVITY_DATE = D.ACTIVITY_DATE
 AND U.CURRENCY_CODE = D.CURRENCY_CODE
LEFT JOIN SHOPIFY_CONTROL.META.STORE_REGISTRY R
  ON R.STORE_KEY = D.STORE_KEY;

-- 5. Published surfaces -------------------------------------------------------
--    Fixed names the shared monitoring, reconciliation, and BI read. Switching
--    to the Openflow path replaces only these two views.
CREATE OR REPLACE VIEW SHOPIFY_CONTROL.META.V_DAILY_SHOP_ACTIVITY
COMMENT = 'Published contract surface. Native path implementation.'
AS
SELECT
  STORE_KEY, SHOP_URL, ACTIVITY_DATE, CURRENCY_CODE,
  ORDERS_PLACED, ORDERS_CANCELLED, UNITS_SOLD,
  GROSS_SALES, DISCOUNTS, REFUNDS, NET_SALES,
  SHIPMENTS_CREATED, SHIPMENTS_SUCCESS, SHIPMENTS_DELIVERED
FROM SHOPIFY_NATIVE.ANALYTICS.DAILY_SHOP_ACTIVITY;

CREATE OR REPLACE VIEW SHOPIFY_CONTROL.META.V_STORE_FRESHNESS
COMMENT = 'Published ops surface: hours since the newest order update per active store. Native path implementation.'
AS
SELECT
  R.STORE_KEY,
  R.SHOP_DOMAIN,
  R.BUSINESS_OWNER,
  R.LAST_QUALIFIED_AT                                       AS PIPELINE_READY_AT,
  MAX(O.UPDATED_AT)                                         AS LAST_ORDER_UPDATE,
  DATEDIFF('hour', MAX(O.UPDATED_AT), CURRENT_TIMESTAMP())  AS HOURS_SINCE_LAST_UPDATE,
  COUNT(O.ORDER_ID)                                         AS ORDERS_LOADED
FROM SHOPIFY_CONTROL.META.STORE_REGISTRY R
LEFT JOIN SHOPIFY_NATIVE.ANALYTICS.ORDERS O
  ON O.STORE_KEY = R.STORE_KEY
WHERE R.IS_ACTIVE
GROUP BY R.STORE_KEY, R.SHOP_DOMAIN, R.BUSINESS_OWNER, R.LAST_QUALIFIED_AT;

-- 6. Read access for analysts --------------------------------------------------
CREATE ROLE IF NOT EXISTS SHOPIFY_ANALYST
  COMMENT = 'Read-only access to the Shopify analytics layer';
GRANT USAGE  ON DATABASE SHOPIFY_NATIVE             TO ROLE SHOPIFY_ANALYST;
GRANT USAGE  ON SCHEMA SHOPIFY_NATIVE.ANALYTICS     TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES    IN SCHEMA SHOPIFY_NATIVE.ANALYTICS TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA SHOPIFY_NATIVE.ANALYTICS TO ROLE SHOPIFY_ANALYST;
GRANT USAGE  ON WAREHOUSE SHOPIFY_PIPELINE_WH       TO ROLE SHOPIFY_ANALYST;
GRANT USAGE  ON DATABASE SHOPIFY_CONTROL            TO ROLE SHOPIFY_ANALYST;
GRANT USAGE  ON SCHEMA   SHOPIFY_CONTROL.META       TO ROLE SHOPIFY_ANALYST;
GRANT SELECT ON VIEW SHOPIFY_CONTROL.META.V_DAILY_SHOP_ACTIVITY TO ROLE SHOPIFY_ANALYST;

-- 7. Verify -------------------------------------------------------------------
SELECT COUNT_IF(STATUS <> 'OK') AS CONTRACT_VIOLATIONS
FROM SHOPIFY_CONTROL.META.V_CONTRACT_CONFORMANCE;

SELECT STORE_KEY, ACTIVITY_DATE, CURRENCY_CODE, ORDERS_PLACED, UNITS_SOLD,
       NET_SALES, SHIPMENTS_CREATED, SHIPMENTS_SUCCESS
FROM SHOPIFY_CONTROL.META.V_DAILY_SHOP_ACTIVITY
ORDER BY ACTIVITY_DATE DESC, STORE_KEY
LIMIT 50;
